### ISSUE TITLE
[BUG] Fulltext not loading

### ISSUE THREAD

**Issue by csidirop** [kitodo/kitodo-presentation#1053]
## Description

The latest code from main (2dfbef8c44c3ccc1bbe507d2b6eb1a95a0a96cb9), together with the latest DFG-Viewer code (https://github.com/slub/dfg-viewer/commit/2af0d45027c5892059fcbec3acacd2d9b0956d5a) and the latest slub_digitalcollections code (including these two PRs (https://github.com/slub/slub_digitalcollections/pull/55 and https://github.com/slub/slub_digitalcollections/pull/51)) does not load the fulltext correctly:

![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/8d7f9080-48cc-4f80-996b-784ed22d15db)

Log: 
`Core: Error handler (FE): PHP Warning: Illegal string offset 'location' in /var/www/typo3/public/typo3conf/ext/dlf/Classes/Controller/PageViewController.php line 11` 
`Core: Error handler (FE): PHP Warning: Illegal string offset 'mimeType' in /var/www/typo3/public/typo3conf/ext/dlf/Classes/Controller/PageViewController.php line 119`

Clicking the fulltext-button (hide and show again) changes nothing.

This error exists since 9583e9208752c284921e9f3884d9ac2fcab9980a .

## Environment

 -  OS version: Debian (in Docker)
 -  RDBMS version: Maria DB (MySQL 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204)
 -  Apache Solr version: -
 -  TYPO3 version: 10.4.38-dev
 -  PHP version: 7.4.33

**Comment by beatrycze-volk** [comment]
I would suspect that this https://github.com/kitodo/kitodo-presentation/pull/1051 fixes the problem.

**Comment by csidirop** [comment]
Thanks, thats it
