### ISSUE TITLE
Error in Administration Log of typo3

### ISSUE THREAD

**Issue by BFallert** [kitodo/kitodo-presentation#1061]
## Description

In the errorlog of Typo3 I see the following error message: 
`ERROR | Error handler | Core: Error handler (FE): PHP Warning: Invalid argument supplied for foreach() in /var/www/typo3/packages/dlf/Classes/Controller/TableOfContentsController.php line 306
`
## Reproduction

Steps to reproduce the behaviour:

I use the DFGViewer PageView in my installation. 

1. Go to PageView of a monographie 
2. open typo3 as admin
3. open Administration log

## Expected Behavior

No Error Message in Administration Log

## Source Code of the Error
The error is in the lines:

    private function setTitle(array $entry): string
    {
        if (empty($entry['label']) && empty($entry['orderlabel'])) {
            foreach ($this->settings['titleReplacements'] as $titleReplacement) {
                if ($entry['type'] == $titleReplacement['type']) {

the variable `$this->settings['titleReplacements']` is NULL, don't know why.

## Environment

 - OS version: Linux 5.10.0-26-cloud-amd64  SMP Debian 5.10.197-1 (2023-09-29) x86_64
 - RDBMS version: MariaDB 10.5.21-MariaDB-0+deb11u1 Debian 11
 - Apache Solr version: 8.11.2
 - TYPO3 version: 10.4.37
 - PHP version: 7.4.33

## Additional Information

For troubleshooting I have made the following adjustments in the Typo3 configuration file LocalConfiguration.php:

    'SYS' => [
        'displayErrors' => 1,
        'debugExceptionHandler' => 'TYPO3\\CMS\\Core\\Error\\DebugExceptionHandler',
        'exceptionalErrors' => E_ALL ^ E_NOTICE ^ E_WARNING ^ E_USER_ERROR ^ E_USER_NOTICE ^ E_USER_WARNING,
        ...

**Comment by beatrycze-volk** [comment]
Thanks for the report.

It looks like the missing setting from setup.typoscript: https://github.com/search?q=repo%3Akitodo%2Fkitodo-presentation%20titleReplacements&type=code

Could you check if you have this included?

**Comment by BFallert** [comment]
Sorry for my late reply. I had entered the configuration in the presentation area. However, I had to transfer these settings to the dfg viewer, then the error message disappeared. Thanks for your help.
