### ISSUE TITLE
[BUG] New Tenant errors

### ISSUE THREAD

**Issue by csidirop** [kitodo/kitodo-presentation#1082]
## Description

Clicking on an non cofig-folder shows following error: `Validation failed while trying to call Kitodo\Dlf\Controller\Backend\NewTenantController->errorAction(). ` which then shows following error on the configuration folder: `An error occurred while trying to call Kitodo\Dlf\Controller\Backend\NewTenantController->errorAction()`

Edit: now it got this message additionally `Return value of Kitodo\Dlf\Controller\Backend\NewTenantController::errorAction() must be an instance of Psr\Http\Message\ResponseInterface, string returned`

## Reproduction

Steps to reproduce the behaviour:

0. Get newest code (in my case 4dd7001b643607fb879c006288e8aa3a139fd5d0)
1. Go to BE -> New Tenant -> click on any page or non presentation config folder:
    * ![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/a58bb0a3-7660-4464-9e94-918ec9e0905b)
2. Go to BE -> New Tenant -> click on your presentation config folder:
    * ![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/84f254ae-50a9-400c-805a-9374f98d4f5f)

## Environment

 -  OS version: Debian (in Docker)
 -  RDBMS version: Maria DB (MySQL 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204)
 -  Apache Solr version: -
 -  TYPO3 version: 10.4.38-dev
 -  PHP version: 7.4.33

**Comment by csidirop** [comment]
Interestingly this error disappears and the correct message string is shown if I reverse the last changes made to `errorAction()` (9b4521b55fff17e88f91dc54ac9b77f1d480bb3e and 0be9160a566e093c0b8394454e52a38186549300 [(changes)](https://github.com/kitodo/kitodo-presentation/commit/0be9160a566e093c0b8394454e52a38186549300#diff-0abb3a5900bfb4fe46638fafc0214fda4be5326c6fecb0b8201cc733c2d8fc80)).

The empty function works fine for me.

```
    public function errorAction(): void
    {
    }
```

Btw. the same error happens, if we remove the function in `NewTenantController` and the parents function is called implicitly.

Why do we need the call to the inherited function?

**Comment by sebastian-meyer** [comment]
With the empty function we had PHPStan complaining about wrong return type, because the parent function returns `ResponseInterface`, but our function returned `void`.

Yeah, we shouldn't make this more complicated than necessary. If it works with the empty function we should revert the changed and add an ignore-comment for PHPStan instead.

**Comment by csidirop** [comment]
Okay I see now. I just wasn't sure if the empty function was just a workaround. To be honest, I couldn't see why this works 😅

But If we would do it this way, I can provide a quick PR. What does @beatrycze-volk thinks?

**Comment by beatrycze-volk** [comment]
Sure, if @sebastian-meyer is fine with it :)
