### ISSUE TITLE
Incorrect display of page numbers in table of contents 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-presentation#110]
The display of page numbers in the table of contents does not work correctly in Goobi.Presentation. 

How it is: 
It seems as if all page numbers are displayed in the middle of the table of contents. 
![page_numbers](https://cloud.githubusercontent.com/assets/14835770/13742202/ce695922-e9da-11e5-9db6-702035e79b7b.jpg)

How it should be: 
Either the page numbers should be displayed for each element (chapter, titele page, ...), or no page numbers should be displayed at all.

**Comment by sebastian-meyer** [comment]
This is actually a bug in the CSS design of the SLUB Digital Collections. Goobi.Presentation produces the correct markup.

Paging @gnuj

**Comment by gnuj** [comment]
Fixed this in the SLUB Template extension. Doesn't belong to this project.
