### ISSUE TITLE
[BUG] Search word highlighting does not work (`tx_dlf[highlight_word]`)

### ISSUE THREAD

**Issue by csidirop** [kitodo/kitodo-presentation#1127]
## Description

With prior versions (~presentation v2?) there was a optical highlight for searched words in opened documents. This is missing in the last releases for at least presentation v3.4.3:

![comparisson](https://github.com/kitodo/kitodo-presentation/assets/43964592/e1398707-23d5-4ff1-a13b-a275033358d4)
Here in detail:
![detail](https://github.com/kitodo/kitodo-presentation/assets/43964592/9d00bc72-250c-491e-a0d9-7591f9544ac2)

**Left (v2.2.0):** https://digi.bib.uni-mannheim.de/suchergebnis/seitenansicht-suche/?tx_dlf[id]=3693&tx_dlf[page]=76&tx_dlf[highlight_word]=Exprorektor
 
**Right (master branch):** https://playground.bib.uni-mannheim.de/werksansicht?tx_dlf[highlight_word]=Exprorektor&tx_dlf[id]=2210&tx_dlf[page]=76
(Dev instance, might change, or be broken)

It seams that the `tx_dlf[highlight_word]` query is ignored.

## Reproduction

Steps to reproduce the behaviour:

1. Setup and old (~v2.x) and a new presentation instance
2. Index a document with fulltext
3. Search for word that exists
4. There should be some hits
5. Take on and open it
6. The old instance will highlight the search prompt in the documents overlay, the new one doesn't.

## Expected Behavior

Highlight the search prompt in the documents overlay.

**Comment by stweil** [comment]
Please add also a milestone.
