### ISSUE TITLE
[BUG] PR#1116 somehow broke my viewer. When opening a document with a fulltext it just shows "Volltext wird geladen"

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#1151]
This PR somehow broke my viewer. When opening a document with a fulltext it just shows "Volltext wird geladen"

![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/ff1cf38c-5035-48e3-91b0-1915511b035a)

Reverting this fixes that issue. In detail its the changes in [FulltextControl.js](https://github.com/kitodo/kitodo-presentation/pull/1116/files#diff-23b1fd74dbf112aa8dd3fbfcfe1529e09f9f936923b7b5943e763441fd2bee39). I have not yet looked into these changes, but I will as soon I found some time.

But I believe that the DFG-Viewer could be the reason why you didn't notice it. I did not test it with the presentation viewer.

_Originally posted by @csidirop in https://github.com/kitodo/kitodo-presentation/issues/1116#issuecomment-1914536846_

**Comment by csidirop** [comment]
@BFallert is already investigating that issue.

**Comment by csidirop** [comment]
The two PRs should fix the issue. The issue was that the correct id was not set in the first place after the code change, and then that DFG-Viewer overwrites presentations setting if used together.

**Comment by beatrycze-volk** [comment]
It fixes the problem, I will now merge PR to DFG-Viewer.
