### ISSUE TITLE
Activate GitHub Discussions for this repository

### ISSUE THREAD

**Issue by michaelkubina** [kitodo/kitodo-presentation#1187]
### Problem

We have several issues open, that have a question label, and that are not necessarily real issues. This results in discussions about behaviour or configurations of kitodo-presentation. Some feature requests result in discussions as well, as they have certain dependencies in the code or have underlying restrictions, that are not obvious. Additionally its often not quite clear, what parts in the code are currently being developed or rewritten/restructured. So it would be benefitial to have a forum to talk about all such things beforehand.

The issue tracker does not seem like the right place to do this. If theres a uncertainty if something is a actually a bug or a the result of a misconfiguration, a discussion would help to identify it, so a precise issue can be written if its actually a bug. Discussing ideas or shortcomings can result in more precise feature requests as well, since the practicability and usefullness have been examined.

The issue tracker sets a certain (psychological) barrier, to just talk about visions and goals. This can also lead to less engagement and interaction of all participants.

### Proposed Solution
Activate GitHub discussions in this repository, so that we have a place to talk about whats on our minds.

**Comment by sebastian-meyer** [comment]
That's an easy request! I've activated discussions for this repository. Feel free to [head over and start discussing](https://github.com/kitodo/kitodo-presentation/discussions)!

**Comment by csidirop** [comment]
Good suggestion, thank you!
