### ISSUE TITLE
Latest released version breaks TYPO3 extension manager

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#119]
Goobi.Presentation CE 1.3.0 which is also the latest version available from TYPO3 Extension Repository breaks the TYPO3 extension manager when it is installed. The breakage is reported in the Apache2 error.log:

```
PHP Fatal error:  require_once(): Failed opening required 'common/class.tx_dlf_helper.php' (include_path='/var/www/html/typo3/contrib/pear/:.:/usr/share/php:/usr/share/pear') in /var/www/html/typo3temp/ExtensionManager/UpdateScripts/ext_updatef6b292186acec66f73619c4c401cd408.php on line 25, referer: https://localhost/typo3/backend.php
```

This issue was already fixed in commit 8cf6ded617564c000724380a057d8beaec177ed1, but there is currently no released version which includes that fix.

As a workaround, it is possible to edit (or remove) the buggy file `typo3temp/ExtensionManager/UpdateScripts/ext_update*.php`.

**Comment by stweil** [comment]
In addition, commit c2e2666297e88fc82ad7e5d9a7b67763e8ed810e is needed.

The current script tries to read a database table which does not exist on a fresh installation of Goobi.Presentation:

```
Invalid database result detected: function TYPO3\CMS\Core\Database\DatabaseConnection->sql_num_rows called from file po3temp/ExtensionManager/UpdateScripts/ext_updatef6b292186acec66f73619c4c401cd408.php in line 87.
```

**Comment by stweil** [comment]
In addition, commit bd1f32b071911708f03531a11bc2dac7e1183363 is needed.

**Comment by stweil** [comment]
In addition, commit 50e4929408edeea85c7bf2c033e1ea851854fd68 is needed.

**Comment by sebastian-meyer** [comment]
Thank you for the bug report!
We are planning to release a new version before May 12th, which includes all those fixes.
