### ISSUE TITLE
[BUG] Reindexing options -l and -b work not with -c (or long versions) or -a

### ISSUE THREAD

**Issue by BFallert** [kitodo/kitodo-presentation#1215]
### Problem

At the moment it is not possible to reindex a large collection with -l (--index-limit) and -b (--index-begin). It is only possible to reindex the whole dataset. 
If the reindexing options -l (--index-limit) and -b (--index-begin) are used, a simultaneously specified parameter -c (--coll) is ignored. 
If -a (--all) is used together with the parameters -l (--index-limit) and -b (--index-begin), these two parameters are ignored.

### Proposed Solution
It should also be possible to reindex a large collection using -l and -b. If the current behavior is desired, the documentation would have to be adapted. 

## Additional Context
https://github.com/kitodo/kitodo-presentation/blob/0dd0bfef744d25fb8aebc65190422f7f90011069/Classes/Command/ReindexCommand.php#L157-L186

**Comment by beatrycze-volk** [comment]
Can this issue be closed or is there still something missing?

**Comment by sebastian-meyer** [comment]
Yes, this is fixed. I just forgot to link the issue to the pull request. Sorry!
