### ISSUE TITLE
Download of images with standard browser tools (right click -> save).

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#132]
In Kitodo.Presentation 2.0 with OpenLayers 3.0 it's not possible anymore to use "Right Click" to save the original image. Only a low quality version "Download.png" is offered.

Users of the previous version are used to this unspecified feature. Even though the filegroup "DOWNLOAD" is intended for this purpose.

This has to be discussed and implemented.

**Comment by sebastian-meyer** [comment]
This is due to the way OpenLayers works especially in conjunction with image servers like IIP and IIIF.

I am closing this since there is a tool for the toolbox plugin which allows downloading of single images.
