### ISSUE TITLE
[BUG] setCPid() must be of the type int, null given

### ISSUE THREAD

**Issue by fschoelzel** [kitodo/kitodo-presentation#1329]
## Description

_-- This Issue might be in the wrong Extension --_

The `settings` array of the `Slub/Dfgviewer/Controller/UriController` is empty. So `$doc->cPid` is set to `null` instead of `0` if the `storagePid` is empty. (in this case the whole array is)
Without the cast to (int) it throws an error.

## Reproduction

1. reload the Site

## Screenshots and Examples

![error-cpid-1](https://github.com/user-attachments/assets/0b93e57b-e79a-4d5f-bca4-d5319581333b)
![error-cpid-2](https://github.com/user-attachments/assets/ab657685-efd3-4f27-a758-318160400908)

## Environment

 - OS version: Linux Mint 21 Cinnamon
 - RDBMS version: MariaDB 10.1
 - TYPO3 version: 11.5.38
 - PHP version: 7.4.33
 - Extensions: kitodo/presentation, slub/dfgviewer, slub/slub-digitalcollections

## Additional Context
occurred after merging this PR:
#1324

**Comment by fschoelzel** [comment]
@beatrycze-volk 

- Option 1: we get back to `$doc->cPid = max((int) $this->settings['storagePid'], 0);`
- Option 2: we check for an existing `settings` array and `storagePid` key

**Comment by fschoelzel** [comment]
@beatrycze-volk Did you found a solution?
This PR #1334 did'nt fix my Problem.

**Comment by beatrycze-volk** [comment]
For me it works now. 

> @beatrycze-volk Did you found a solution? This PR #1334 did'nt fix my Problem.

Yes, for me it has fixed the problem. I can now display the document page. Have you cleaned cache? Maybe restart your ddev.
