### ISSUE TITLE
[BUG] Exception when showing metadata of a document

### ISSUE THREAD

**Issue by thomaslow** [kitodo/kitodo-presentation#1343]
## Description

`Argument 1 passed to Kitodo\Dlf\Common\MetsDocument::getLogicalStructure() must be of the type string, array given, called in /var/www/html/kitodo-presentation/Classes/Controller/MetadataController.php on line 313`

Probably related to #1339 and #1317.

## Reproduction

Steps to reproduce the behaviour:

1. Select a document
2. Open page with metadata widget
3. Get Exception

## Expected Behavior

Metadata is shown without exception.

## Environment

- OS version: Linux Docker (docker.io/php7.4-apache)
- RDBMS version: docker.io/library/mariadb:10.11
- Apache Solr version: 9.6
- TYPO3 version: 11.5.39
- PHP version: 7.4

**Comment by sebastian-meyer** [comment]
This is related to #1308.

We urgently need to fix metadata handling (it should be arrays everywhere, because every field can be multi-valued) and make sure, that all semi-fixes like #1317, #1339 and #1344 are reverted.
