### ISSUE TITLE
Add CI for Kitodo.Presentation on GitHub

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#143]
I suggest adding automated static code analysis for pull requests and commits, for example using Scrutinizer. Examples:
- https://scrutinizer-ci.com/g/UB-Mannheim/kitodo-presentation/
- https://scrutinizer-ci.com/g/UB-Mannheim/PalMA/

Example of PR with Scrutinizer:
- https://github.com/UB-Mannheim/PalMA/pull/31

**Comment by sebastian-meyer** [comment]
Done: https://scrutinizer-ci.com/g/kitodo/kitodo-presentation/?branch=master
