### ISSUE TITLE
No fulltext is displayed within pageview on Webserver subdirectory

### ISSUE THREAD

**Issue by frank-ulrich-weber** [kitodo/kitodo-presentation#146]
If Kitodo.Presentation is installed/configured to run on a subdirectory of the Webserver the following line https://github.com/kitodo/kitodo-presentation/blob/master/dlf/plugins/pageview/class.tx_dlf_pageview.php#L185
creates an invalid URL. I think it is possible to avoid this behaviour just by deleting the leading '/'. Am I right or will then arise other problems?

**Comment by sebastian-meyer** [comment]
Unfortunately your proposed fix would cause other issues, for example when using "realurl" extension.

We should use the typolink API to generate the URL and circumvent those issues.

**Comment by albig** [comment]
This has been fixed with 51af8d9800df9cd37eb872f57a8a17a40f4a8192
