### ISSUE TITLE
JavaScript error after adding Page View Map features

### ISSUE THREAD

**Issue by frank-ulrich-weber** [kitodo/kitodo-presentation#147]
After adding Map features within the Page View Plugin the following JavaScript error appears:
"ReferenceError: layers is not defined" within https://github.com/kitodo/kitodo-presentation/blob/master/dlf/plugins/pageview/tx_dlf_pageview.js#L101-L103
The documentation of the method tells me that it is only for fulltext and image manipulation. The Map Features like "OverviewMap" and "ZoomPanel" are not mentioned. Is that just needless code at this place? The createControls_ method is by the way called within the init() method.
https://github.com/kitodo/kitodo-presentation/blob/master/dlf/plugins/pageview/tx_dlf_pageview.js#L305-L307
I comment out that piece of code and everthing is still working without JavaScript errors.

**Comment by sebastian-meyer** [comment]
Should be fixed with #148
