### ISSUE TITLE
location of METS-file with special characters need to be encoded

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#154]
If the location of the METS-file contains special characters as "Umlaute", the METS-file is not loaded and all plugin output is empty.

Example: http://digital.slub-dresden.de/fileadmin/data/330699008/heßFleh_330699008_mets.xml

If you enable the developer log, you receive the error message 

> 	[tx_dlf_document->load(http://digital.slub-dresden.de/fileadmin/data/322151767/meißunsem_322151767_mets.xml)] Invalid file location "http://digital.slub-dresden.de/fileadmin/data/322151767/meißunsem_322151767_mets.xml" for document loading

This is caused by the validation inside GeneralUtility::isValidUrl() used in tx_dlf_document::load().

The location should be (raw)urlencoded after reading from the database.

**Comment by stweil** [comment]
This should be tested with other URLs, too: links to images, full text, pdf, ... which are part of the METS/MODS file.

**Comment by sebastian-meyer** [comment]
Those examples are no longer valid and I can't reproduce the issue. Can someone provide new examples?

(I suspect that this issue was caused because we failed to properly urlencode our ingested URIs. This was fixed some time ago, so maybe this issue doesn't exist anymore.)

**Comment by sebastian-meyer** [comment]
Closed since the issue can't be reproduced anymore.
