### ISSUE TITLE
Box with extended metadata cannot be opened

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-presentation#155]
The box with extended metadata cannot be opened in Kitodo.Presentation, when the button to open the box covers the "navigation area" (see image below). 

This happens when the metadata preview beneath the title is too long. Until now, the only known way to open the metadata box is to scale down or up the browser's content until the button moves out of the navigation area. 

It would be more usable, if either
- a line break is used if the metadata preview covers the navigation area (metadata in two lines) or 
- if the lenghts of the metadata preview is limited in a way that it never covers the navigation area (not all metadata is shown)

Example: [http://digital.slub-dresden.de/id274276038](http://digital.slub-dresden.de/id274276038)

![metadata_box](https://cloud.githubusercontent.com/assets/14835770/23790757/be19fd02-0580-11e7-897e-4dcde8ecb640.jpg)

**Comment by albig** [comment]
This depends on the screen width. 

The layout of the example above is not part of the Kitodo.Presentation extension. This must be adapted in Kitodo layout of this website. In this case of SLUB Dresden.
