### ISSUE TITLE
Change directory structure of extension

### ISSUE THREAD

**Issue by Erikmitk** [kitodo/kitodo-presentation#156]
The repository itself contains the directory `dlf` in which the whole extension is located.

If you want to install it on your local TYPO3 installation you have to clone the repository directly inside the `ext` directory. Otherwise you end up with a structure like `ext/dlf/dlf` which does not work.

The drawback of cloning into `ext` is that any other file/extension that is in there would be in your local `kitodo-presentation` repository as well (as untracked files). That doesn’t make much sense since it should be encapsulated on its own.

You can potentially clone the repo somewhere and then use a symbolic link in the `ext` directory. But even then you’d need an additional (superfluous) directory hierarchy for the extension because the `.git` is a lever higher than the extension itself.

The solution would be to move everything out of the `dlf` directory into the root of the repository. That would be a drastic change to the repository structure so I don’t know the possible repercussions to that move.

**Comment by albig** [comment]
I agree with you. This directory layout is not the way we are used too with other extensions.

The workaround is indeed the checkout somewhere (e.g. `ext`) and make a symbolic link into `kitodo-presentation/dlf/`.

The solution would be, to move everything into the repository root directory as you described it.

**Comment by sebastian-meyer** [comment]
I'll do that as soon as the `basket` feature (#216) is merged to avoid further conflicts.
