### ISSUE TITLE
Add composer.json and class loading information for TYPO3 7

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#163]
In TYPO3 7 the class loading changed completely. The file `ext_autoload.php` is ignored but a section "autoload" in `ext_emconf.php` could be used to provide class locations and help the autoloader.

Even better is to provide a `composer.json` file with autoload information. This makes it possible to use Kitodo.Presentation in composer mode. Running TYPO3 in composer mode makes it easier for deployment and class loading should be even faster.

Read the blogpost of Helmut Hummel: [Changes in class loading in TYPO3 7LTS](http://insight.helhum.io/post/130812561790/changes-in-class-loading-in-typo3-7lts)
and  [COMPOSER AND TYPO3 7LTS](https://usetypo3.com/typo3-and-composer.html).

This issue is related to #156.

**Comment by sebastian-meyer** [comment]
I added a `composer.json` with class autoloading information. But I haven't removed `ext_autoload.php` or any information in `ext_emconf.php` to still keep compatibility with TYPO3 6.2.
Before releasing v3.0.0 and requiring at least TYPO3 7.6 we should fix that, too.

**Comment by sebastian-meyer** [comment]
This should be fixed in compatibility branch [kitodo-presentation/typo3-8+](/kitodo/kitodo-presentation/tree/typo3-8%2B)

**Comment by sebastian-meyer** [comment]
Fixed with #329
