### ISSUE TITLE
Endless recursion when importing from Visual Library

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#17]
Importing data from Visual Library fails with out-of-memory:

```
/var/lib/typo3-dummy/typo3/cli_dispatch.phpsh dlf index -pid 3 -core 1 -doc "http://digi.bib.uni-mannheim.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=17208"
```

The XML data mets:mptr causes an endless recursion because it refers to the same URL.

```
<mets:mptr LOCTYPE="URL" xlink:href="http://digi.bib.uni-mannheim.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=17208"/>
```

**Comment by sebastian-meyer** [comment]
Sorry, I completely missed your bug reports...
Please have a look at the proposed bug fix mentioned above.

**Comment by sebastian-meyer** [comment]
@stweil could you please have a look at this bug and the proposed fix? The next release is scheduled for friday and I'd like to add this fix.

**Comment by stweil** [comment]
Tested-by: Stefan Weil sw@weilnetz.de

That patch works fine for me, thank you. I'm not sure about the coding style (see my comment in the patch).
