### ISSUE TITLE
Add OpenLayers FullScreen Control

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#172]
The current used build of OpenLayers 3 in Kitodo.Presentation the FullScreen control is not included. It should be included in ol3-dlf.json and a new build should be added.

Of course this control must be added in pageview plugin as well to be usable.

**Comment by sebastian-meyer** [comment]
Is this related to this branch: https://github.com/kitodo/kitodo-presentation/tree/fix-172-add-ol-fullscreen?

And is this branch ready to get merged?

**Comment by sebastian-meyer** [comment]
#242 introduced a new OpenLayers build. Is this still relevant?

**Comment by albig** [comment]
#242 doesn't bring the FullScreen control. But we (currently) won't use it anyway.

**Comment by sebastian-meyer** [comment]
Is there any chance that this is fixed anytime in the next months? Otherwise I'd close this issue and delete the branch https://github.com/kitodo/kitodo-presentation/tree/fix-172-add-ol-fullscreen

**Comment by albig** [comment]
I think, we can close this. The real fullscreen mode doesn't help us as we always exit fullscreen mode on paging. This is only useful for single images and maps.
