### ISSUE TITLE
LABEL of physical structMap is ignored; ORDERLABEL is used instead

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#178]
The [METS application profile](http://dfg-viewer.de/fileadmin/groups/dfgviewer/METS_application_profile_2.3.pdf) Version 2.3 describes the  physical document structure as follows:

> The ORDERLABEL attribute can contain the pagination of the
> individual page according to the original.
> The LABEL attribute can include the foliation of the individual
> page or the specification of record side and track number.

In Kitodo.Presentation, the function _getPhysicalPages() ignores the LABEL and sets "label" as ORDERLABEL if present.

https://github.com/kitodo/kitodo-presentation/blob/master/dlf/common/class.tx_dlf_document.php#L1930

I would suggest, to use LABEL if present, else ORDERLABEL if present, else empty string.

**Comment by sebastian-meyer** [comment]
We should set ORDERLABEL and LABEL in _getPhysicalPages() and use whatever is reasonable later.
________________________________
Von: Alexander Bigga
Gesendet: Mon May 29 12:43:49 GMT+02:00 2017
An: kitodo/kitodo-presentation
Cc: Subscribed
Betreff: [kitodo/kitodo-presentation] LABEL of physical structMap is ignored; ORDERLABEL is used instead (#178)


The METS application profile<http://dfg-viewer.de/fileadmin/groups/dfgviewer/METS_application_profile_2.3.pdf> Version 2.3 describes the physical document structure as follows:

The ORDERLABEL attribute can contain the pagination of the
individual page according to the original.
The LABEL attribute can include the foliation of the individual
page or the specification of record side and track number.

In Kitodo.Presentation, the function _getPhysicalPages() ignores the LABEL and sets "label" as ORDERLABEL if present.

I would suggest, to use LABEL if present, else ORDERLABEL if present, else empty string.

**Comment by sebastian-meyer** [comment]
See #205: `tx_dlf_document->physicalStructureInfo` now contains `@LABEL` and `@ORDERLABEL`.
