### ISSUE TITLE
Language Overlay of Metadata and Structures not working as expected

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#192]
Currently it is not possible to translate the labels like "Title" of the tx_dlf_metadata table or "Strukturtyp" of the tx_dlf_structures.

Usually you copy a table row and insert it again on the same page. You edit the copy and change the language to the overlay language AND you select the default label.
If this is done, the Metadata-entry is displayed twice: One time with the default label. The second time with the dummy index_name ("title0).

**Comment by sebastian-meyer** [comment]
Just leaving this here for later reference:
https://docs.typo3.org/typo3cms/FrontendLocalizationGuide/singlehtml/#core-support-for-localization
