### ISSUE TITLE
Fulltext plugin doesn't check for supported XML format

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#196]
Currently Kitodo.Presentation supports only fulltexts in ALTO-XML format. The support of TEI-XML will be developped soon.

The plugin activates the fulltext feature without checking the file format.

http://dfg-viewer.de/show/?tx_dlf%5Bpage%5D=7&tx_dlf%5Bid%5D=http%3A%2F%2Fapi.deutsche-digitale-bibliothek.de%2Fitems%2FCPUZ346S6S5FJDLBRXURTOSFGVLFYMQH%2Fsource&tx_dlf%5Bdouble%5D=0

This should be improved.

**Comment by sebastian-meyer** [comment]
Duplicate of #197

**Comment by albig** [comment]
Actually this is not a duplicate.

#196 is related to toolbox->tool->fulltext plugin
#197 is related to pageview plugin

Of course it should be fixed together as it's one topic.
