### ISSUE TITLE
Missing format validation of fulltext parsing

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#197]
Kitodo.Presentation supports fulltexts in ALTO-XML format. TEI will be supported soon.

On parsing the given file, there is no check the format is supported.

The result are several Javascript errors like this:

`Uncaught TypeError: Cannot read property 'getTextblocks' of undefined`

This should be improved. Maybe together with the TEI-Feature. Introducing this feature, we have to decide, which parser should be used depending on the file format.

**Comment by sebastian-meyer** [comment]
Paging @tinrie about this.
