### ISSUE TITLE
Scanned pages not rendered in case site language is English 

### ISSUE THREAD

**Issue by GeraldHuebschSLUB** [kitodo/kitodo-presentation#206]
In case the site language of www.slub-dresden.de is set to English (using the flag icon in the tool menu on the top), Kitodo.Presentation does not render scanned pages of the selected work. Only thumbnail images displayed by the page browser on the bottom are visible. The following link can be used to reproduce the effect: http://digital.slub-dresden.de/en/workview/dlf/177620/1/0/.

**Comment by sebastian-meyer** [comment]
This was just a configuration error on digital.slub-dresden.de and not a software bug.
