### ISSUE TITLE
Javascript Error in pageview plugin (basket feature)

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#239]
In current master, there is a javascript error in tx_dlf_pageview.js used by pageview plugin:

`Uncaught TypeError: Cannot read property 'condition' of undefined (tx_dlf_pageview.js:424)`

![kitodo_presentation_pageview_error](https://user-images.githubusercontent.com/3354500/33897539-00889e2c-df66-11e7-839e-c1887af79c37.png)

**Comment by christopher-timm** [comment]
This Javascript error occurs if the OpenLayer build has not all required classes.
It wasn't possible for me to build the ol3-dlf.js with the ol3-dlf.json. But I included the required classes in the ol3-dlf.json. Unfortunately without testing.
On the other hand with the full ol3.js this error doesn't occur.

**Comment by albig** [comment]
Ok. So we need to rebuild the openlayers build before the next release.

**Comment by albig** [comment]
@frank-ulrich-weber If you fix this issue: please follow the instruction in Readme.md: https://github.com/kitodo/kitodo-presentation/blob/master/dlf/lib/OpenLayers/README.md
We need to use the SLUB fork and should investigate later on, if we could upgrade OL3.

**Comment by sebastian-meyer** [comment]
Fixed with #242
