### ISSUE TITLE
Using reserverd word STORED (MySQL 5.7.6 >=) as column name within table tx_dlf_metadata

### ISSUE THREAD

**Issue by frank-ulrich-weber** [kitodo/kitodo-presentation#240]
The fix #151 is not sufficiant, because we still run into SQL-Errors when changing and saving the field stored within the metadata configuration of the backend e.g. class.tx_dlf_tcemain->processDatamap_postProcessFiledArray() . The result of my investigation is to rename the field (to stored_within_index?), becaus otherwise we always have to take care of writing \`stored\`. We have to do something like Select \`stored\` as \`stored\`... (e.g tx_dlf_indexing->LoadIndexConf()) that we don't get a problem with the DataHandler on checkStoredRecord(). Other ideas or notes? I prepare the fix, if we come to a consistent decision.

**Comment by albig** [comment]
Writing \`stored\` is not sufficiant in all situations. We noticed this already and I think, we need to rename the column. I would prefer something like `index_stored` and maybe we should prefix all other index-related fields with `index_` as well.

**Comment by lutzhelm** [comment]
The backticks don't even seem to fix the problem for the create statement - if I try to activate the extension, all tables but tx_dlf_metadata are created, tx_dlf_metadata is missing afterwards without any warning messages or log entries.

**Comment by sebastian-meyer** [comment]
I'd like to keep the column names consistent, so I prefer the proposal of @albig to rename all index-related columns to `index_*`.

**Comment by sebastian-meyer** [comment]
Paging @chrizzor about this, because he recently stumbled over this issue, too.

**Comment by frank-ulrich-weber** [comment]
tokenized, stored, indexed, boost, autocomplete?

**Comment by frank-ulrich-weber** [comment]
I'm not sure about how to rename columns while updating the extension on existing installations? Some hints? Thanks!

**Comment by albig** [comment]
This can be done in class.ext_update.php. This is offered in the extension manger if the access() method returns TRUE. There is an example inside of an update of the metadata config.

**Comment by sebastian-meyer** [comment]
Fixed with #247
