### ISSUE TITLE
Missing icons in TYPO3 backend

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#260]
The TYPO3 list view does not show icons for the Kitodo records, for example for the "Mandanten" record. We get this issue in 1.3.0 ~~and 2.2.0~~ (2.2.0 worked in a test done 2018-01-18).

![missing-icon](https://user-images.githubusercontent.com/6734573/34518860-b663ebee-f081-11e7-9b98-8591e4bd8a0c.png)

**Comment by stweil** [comment]
Maybe related: these icon files which are [used in the code](https://github.com/kitodo/kitodo-presentation/search?utf8=✓&q=iconfile) (see `git grep iconfile`) are missing in the [source tree](https://github.com/kitodo/kitodo-presentation/tree/master/res/icons):

- res/icons/txdlfbasket.png
- res/icons/txdlfemail.png
- res/icons/txdlfprinter.png
- res/icons/txdlfreport.png

**Comment by stweil** [comment]
It looks like the four missing icons are part of the basket feature (unrelated to my initial issue). @chrizzor, what about those icons?

**Comment by albig** [comment]
I cannot reconstruct your issue. Your example with the library ("Mandanten") table is working for me in TYPO3 6.2 and 7.6 with Kitodo.Presentation 2.2.0. The file which is loaded in this case is /typo3conf/ext/dlf/res/icons/txdlflibraries.png, which is available.

![typo3 typo3 cms 7 6 23 1](https://user-images.githubusercontent.com/3354500/35111829-7ac9a770-fc7c-11e7-9cf9-7dd6ebf64e68.png)

Could you inspect with your browser, which file should be loaded in your case?

**Comment by stweil** [comment]
I just tested again with both versions of Kitodo.Presentation. While the 1.3.0 instance still shows the problem, 2.2.0 now looks good. Maybe a cache clean up had fixed the problem there?

**Comment by stweil** [comment]
There remains the inconsistency between code and available images for the basket feature (mentioned above). Should that be a new issue, or can we handle it here? If we create a new issue, then the current issue can be closed: we don't need an update for 1.3.x.

In addition, the Kitodo icons on the left side (txdlfindexing.png, txdlfmodules.png, txdlfnewclient.png) use a design which does not fit with other TYPO3 icons there. But that's only cosmetics.

**Comment by christopher-timm** [comment]
I added the missing icons again. I didn't notice that they were removed by the revert commit.

**Comment by stweil** [comment]
Thank you. Then I can close this issue here.
