### ISSUE TITLE
OAI sets don't work for manually created collections

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#271]
Pull request #261 introduced an index based handling of OAI sets. This depends on either having a defined Solr query for each OAI set or searching the index for the `index name` of the collection. Since manually created collections are not referenced in the METS files, they are not indexed and therefore can't be found by searching for the collection's `index name`.
In this case a query for the UIDs of the collection's documents has to be performed instead.

**Comment by sebastian-meyer** [comment]
I suggest refactoring the indexing process: whenever a document gets indexed, all currently referenced collections are queried from the database and their `index names` added to the index.
Likewise, whenever someone adds or removes a document from a collection, that document has to be reindexed (via hook).

That way we always have an index which is consistent with the database and we can reliably query all collections from the index.

**Comment by albig** [comment]
This may work. In the dlf_indexing class it could be sufficiant to change the line
`$solrDoc->setField('collection', $metadata['collection']);` and set the collections to the values stored in the database.
In the hook we do not need to change anything (hopefully). All "update" does an reindexing anyhow. Isn't it?

**Comment by sebastian-meyer** [comment]
Updating a document triggers reindexing, but updating a collection doesn't. I'll try to change that.
