### ISSUE TITLE
Missing information on the required/supported Typo3 version

### ISSUE THREAD

**Issue by dmj** [kitodo/kitodo-presentation#275]
The README provides no information on the required or supported Typo3 versions. I had to check the issue tracker and find #264 in order to find out that we should start with Typo3 7 LTS.

**Comment by albig** [comment]
The requirements are written in the [extension repository](https://extensions.typo3.org/extension/dlf/). This is usually the first point to start. These requirements are took from ext_emconf.php. If a composer.json is present, must keep the requirements too.

**Comment by dmj** [comment]
Having no experience with Typo3 whatsoever I did not know that there even is an Typo3 extension repository. I'm not interested in Typo3, after all. I read that Kitodo.Presentation depends on Typo3, went to the Typo3 homepage and was presented with three different version to install. I then turned back to Kitodo.Presentation to look up the version required or supported.
