### ISSUE TITLE
Why does the TOC plugin flexform configuration require a template file?

### ISSUE THREAD

**Issue by lutzhelm** [kitodo/kitodo-presentation#276]
`//templateFile/TCEforms/config/minitems` is set to '1' in `plugins/toc/flexform.xml` although the plugin uses the default template if no template file is provided, and this template works fine, as far as I can see.

So is there any reason I don't see? Or should this be changed?

**Comment by sebastian-meyer** [comment]
You are right, this should be `minitems=0`
