### ISSUE TITLE
dlfUtils.buildImageV2() requires "tiles" which is optional according to specification

### ISSUE THREAD

**Issue by lutzhelm** [kitodo/kitodo-presentation#279]
According to the IIIF Image API specification, the the `tiles` property for the IIIF V2 info.json is optional. Missing `tiles` lead to an "undefined"-error in `dlfUtils.buildImageV2()`, though.

Possible Solution: If `tiles` is missing there have to be made assumptions about default values that the image source should use. In theory, these values should depend on the compliance level and possibly additionally supported features of the image server according to the profile. The features that the ol iiif source uses are `regionByPx` and `sizeByPct`, contained in levels 1 and 2. But since it does not look like the source supports level 0 compliance at all, any reasonable default values should be fine.

I could provide a pull request for that solution, with a default tilesize of 256x256 (that's what `dlfUtils.createOl3Layers()` assumes anyway) and the default scaleFactors 1, 2, 4, 8, 16 in case `tiles` is missing.

**Comment by sebastian-meyer** [comment]
Assuming a default tilesize of 256 seems reasonable. Since the IIP protocol doesn't provide a tilesize either, we already assume a tilesize of 256 there, too.
