### ISSUE TITLE
Page View Plugin doesn't work out-of-the-box

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#304]
Since the third-party extension `t3query` is no longer compatible with newer versions of TYPO3, we removed the dependency, but failed to find a proper alternative to ensure loading of the jQuery library prior to initializing OpenLayers in the Page View Plugin.
Recent versions of TYPO3 come with their own jQuery library, so we should rely on that. We need to implement it in a way that the Page View Plugin ensures loading of the jQuery library.

**Comment by albig** [comment]
That's not true. If you include the static template - as you should do, jQuery is included via CDN or from dlf. Current Javascript in Kitodo.Presentation is only working with jQuery 2.x.
The TYPO3 jQuery library is IMHO intended for backend modules only.

**Comment by sebastian-meyer** [comment]
Thanks for the quick reply! The static template was added, but the Page View Plugin didn't show anything. The Chrome developer console showed Javascript errors hinting at a missing jQuery library.
I'll have another look at it!

**Comment by sebastian-meyer** [comment]
I can't reproduce this issue. Even with a blank minimal installation of TYPO3 8.7 the plugin works out-of-the-box.
