### ISSUE TITLE
IIIF viewer functionality not available in Internet Explorer

### ISSUE THREAD

**Issue by lutzhelm** [kitodo/kitodo-presentation#310]
While trying to test my recent JavaScript changes with IE11 I noticed that the existing code didn't work in the first place. It fails at least due to missing support for `String.prototype.endsWith()`.
https://github.com/kitodo/kitodo-presentation/blob/067f23017dc8cc4c3b73d7ad5305cf72251fbff3/plugins/pageview/tx_dlf_utils.js#L328

I don't know if the IE is still relevant at all but I could imagine that some institution / organization environments are still stuck with it.

**Comment by sebastian-meyer** [comment]
Do you know of a reasonably simple workaround for this issue?

**Comment by lutzhelm** [comment]
I guess polyfilling the method does not qualify as the most simple workaround. However, this seems to have been the only issue in IE 11.
