### ISSUE TITLE
Image download tool in Toolbox plugin offers IIIF image base URI in default configuration

### ISSUE THREAD

**Issue by lutzhelm** [kitodo/kitodo-presentation#311]
The default `fileGrpsImageDownload` in plugins/toolbox/flexform.xml is the same as the default values for `fileGrps`: `MIN,DEFAULT,MAX`. If a METS/MODS file contains IIIF images in those `mets:fileGrp`s, the image download plugin will simply link the given IIIF image base URI - which results in an error or in a redirect to the image info.json.

It's easy to generate an actual image link to `full/full/0/native.jpg` or `full/full/0/defaut.jpg`, but for the necessary distinction between IIIF image API 1 and 2, an additional server side request for the info.json would be needed - besides the already required client side request.

I suggest to resolve this issue for IIIF image with the necessary changes to view IIIF manifests as those changes will introduce functionality to access IIIF resources more easily - and I have to solve the issue for the display of IIIF manifests anyway.

I guess the download issue also occurs for IIP and Zoomify images.

**Comment by sebastian-meyer** [comment]
Instead of requesting the `info.json` from the server, we could just check the given `MIMETYPE` in the METS file to figure out if IIIF is used (see https://github.com/kitodo/kitodo-presentation/blob/master/common/class.tx_dlf_document.php#L396).

**Comment by lutzhelm** [comment]
We need the `info.json` because the full image URL is different for different IIIF versions, and the custom `MIMETYPE` does not tell us anything about it. For version 1.x,  it's `full/full/0/native.jpg`, for version 2.x, it's `full/full/0/default.jpg`, and unfortunately, for the upcoming version 3 it will change again: `full/max/0/default.jpg`.

**Comment by lutzhelm** [comment]
Concerning IIP and Zoomify:

- Full images for IIP can be retrieved by using the `CVT=jpeg` command without any region / size restrictions: http://iipimage.sourceforge.net/documentation/protocol/
- AFAIK full images for Zoomify are not available through any documented requests / parameters. It would be possible to retrieve the tile images at the best resolution on the client side, draw them on a hidden canvas and return the image via data URL, but that is a hack with results of questionable quality.

**Comment by sebastian-meyer** [comment]
Does #336 completely fix this issue?

**Comment by lutzhelm** [comment]
As far as the original issue and IIIF are concerned, yes, and it also contains a fix for IIP.

I don't know if there is a solution for Zoomify beyond disabling the image download for Zoomify all together.
