### ISSUE TITLE
Fulltext highlight features are misplaced for IIIF images

### ISSUE THREAD

**Issue by lutzhelm** [kitodo/kitodo-presentation#313]
The rectangles for highlighting fulltext lines and blocks are exactly one image height above their correct position within in the image for IIIF images. This is caused by the different View and Source `extend`s used for static JPGs/PNGs and IIIF images. For static images, `[0, 0, width, height]` is used; for IIIF images it's `[0, -height, width, 0]`. Either a distinction between IIIF images and static images has to be made in `dlfAltoParser.prototype.parseGeometry_` or the same extents have to be used.

I do not see a specific reason why different extents are used besides the adoption of unchanged original code from the original IIIF viewer. Besides any other reasons that might exist, before any change to the extent for IIIF images it should be confirmed that this does not impact any other features.

I guess the same problem occurs for IIP and Zoomify images but I have yet to confirm this.

**Comment by lutzhelm** [comment]
There are three options:

- keep the different extents - this would require different handling of image types for the positioning of the highlight features
- always use `[0, 0, width, height]` as extent - this would require changes in https://github.com/slub/ol3/blob/master/src/ol/source/zoomifysource.js because the OpenLayers 3 Zoomify source has no option for extent yet:
https://github.com/slub/ol3/blob/15ede943801f21e201a628f2cfe42219c0e8c779/src/ol/source/zoomifysource.js#L88
- always use `[0, -height, width, 0]` - this would only require adjusting the coordinate calculation once and fix the positioning problem for IIIF, IIP and Zoomify images

I have not found any other feature that is impacted by any changes to the extent but I'd prefer if somebody could please double check.

**Comment by sebastian-meyer** [comment]
The only thing that comes to my mind is the double-page feature. When activating double-page view the second image is positioned with an offset equal to the first image's width. But since changing the extent to `[0, -height, width, 0]` would only affect the height, this shouldn't be a problem.

**Comment by lutzhelm** [comment]
I've checked the double page view; it still seems to work fine.
