### ISSUE TITLE
How do I configure Kitodo to display my own METS files?

### ISSUE THREAD

**Issue by epicfaace** [kitodo/kitodo-presentation#337]
We have archives in METS/ALTO format. How do I load this data into Kitodo Presentation? I can't find the documentation that points to this -- would appreciate some guidance on this.

**Comment by sebastian-meyer** [comment]
Kitodo.Presentation requires at least:

1. A METS file describing an object's logical and physical structure and referencing digital representations of its pages.
2. Embedded descriptive metadata in a XML format (MODS and TEIHDR are supported out-of-the-box, but every other format can be easily configured as well).
3. Optionally per-page text files in ALTO format.

It generally follows the guidelines of the German Research Foundation for METS, MODS and TEI, which can be found [here](http://dfg-viewer.de/en/metadata/).

You can find a lot of examples via the SLUB Dresden OAI interface: https://digital.slub-dresden.de/oai/?verb=Identify

**Comment by BFallert** [comment]
@epicfaace: Maybe the following instructions will help. The manual is in German, I hope that it is still helpful.

https://github.com/kitodo/kitodo-tutorials/blob/master/kitodo3/13_daten-indexieren.md#aufgabe-daten-%C3%BCber-die-kommandozeile-indexieren
