### ISSUE TITLE
Indexing a document generates SQL errors

### ISSUE THREAD

**Issue by jmechnich** [kitodo/kitodo-presentation#342]
### Steps to reproduce
- Install Typo3 and Kitodo.Presentation (+ dependencies)
  - Copy Solr configset from Kitodo.Presentation extension directory to Solr data folder
- Create data folder in Typo3
- Select data folder and click "New Tenant" (note page id for `$PID` below)
- Follow instructions for creating metadata and Solr configuration (note Solr core number for `$COREID` below)
- Run indexer from the cli:
`sudo -u www-data /path/to/typo3/cli_dispatch.phpsh dlf index -doc "http://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-264312570" -pid $PID -core $COREID`

### Expected behaviour
The document is added to Solr and the Kitodo.Presentation database. It should also show up in the list module for the data folder created before.

### Actual behaviour
The indexer call returns without error but the document is not added to Kitodo.Production. The system log shows the following errors:

> SQL error: 'Incorrect integer value: '' for column 'owner' at row 1' (tx_dlf_documents:NEW5cd19ec80fa95) (msg#1.1.12) 
> SQL error: 'Incorrect integer value: '' for column 'oai_base' at row 1' (tx_dlf_libraries:NEW5cd19ec811ef2) (msg#1.1.12)

Installing the devlog extension does not present any additional information.

### System configuration
- Debian 9 stretch
- MySQL Server 5.7.25-1debian9
- Typo3 8.7.25 (installed with composer)
- Kitodo.Presentation 3.0.0 (installed with composer)
- Solr 7.7.1 (installed from tgz)

**Comment by ghost** [comment]
please try disabling mysql strict mode

**Comment by jmechnich** [comment]
This seems to do the trick. Thanks a lot!

**Comment by sebastian-meyer** [comment]
I will provide a fix which hopefully allows using MySQL in strict mode.

**Comment by sebastian-meyer** [comment]
@BFallert Could you please verify if #345 fixes this issue?

**Comment by BFallert** [comment]
I tested it again, but it failed with the same error message.

**Comment by sebastian-meyer** [comment]
Just to be sure: Did you clear the configuration cache before testing it again? Since the (supposed) fix only affects the TCA configuration, it's not enough to just clear the page cache.

**Comment by sebastian-meyer** [comment]
Pinging @BFallert:
Did you clear the configuration cache before testing? I can't reproduce the issue after #345

**Comment by BFallert** [comment]
Had not emptied the cache. After I emptied it now it works

**Comment by sebastian-meyer** [comment]
Thanks for confirming!
