### ISSUE TITLE
Unable to install extension directly from git into Typo3

### ISSUE THREAD

**Issue by jmechnich** [kitodo/kitodo-presentation#346]
I am not sure if this is an actual bug or a feature request but it would be nice for testing purposes if one could just clone the repository to `typo3conf/ext`, enable the extension in the backend and start using it.

Currently there seem to be a few hiccups in the code preventing this:
- `ext_localconf.php`: conditional use of classes in Kitodo namespace, e.g. `if (TRUE === class_exists(\Kitodo\Dlf\Hooks\ExtensionManagementUtility::class)) {...}`, see also for example [here](https://github.com/FluidTYPO3/flux/blob/development/ext_localconf.php)
- `class.ext_update.php`: don't load it  if the extension was not actually installed before as the classes used are unknown to Typo3

As i am not really a Typo3 expert maybe there are alternatives to modifying the code mentioned above, such as autoloading the relevant classes (this seems to be done when using composer).

**Comment by sebastian-meyer** [comment]
Without composer the extension's dependencies would be missing as well. So it is not just an issue of unregistered namespaces/autoloading.

I am not sure if there is a way to make the extension again installable by simply cloning the repository.

**Comment by jmechnich** [comment]
Ok, thanks. This is also not urgent in any way. Maybe I can have a look after everything is running smoothly in our installation.
