### ISSUE TITLE
Respect line breaks when delivering full text

### ISSUE THREAD

**Issue by wrznr** [kitodo/kitodo-presentation#349]
This is a feature request: It would be great if the structural information in general (and line breaks in particular) encoded in specific ALTO XML files could be interpreted (i.e. visualized) in `Kitdodo.Presentation`. Without knowing much about the implementation of the full text view, I'd guess that the XPATH expression and the subsequent text merging in  [Alto.php](https://github.com/kitodo/kitodo-presentation/blob/0ecd515207ff7a67bb6aa43feb8ece85c28017c6/Classes/Format/Alto.php#L35) could be amended to do so.

**Comment by BFallert** [comment]
If you add to your css file the folowing css code you will see the lines like in the original document.

    #tx-dlf-fulltextselection span.textline {
        display: block;
    }

**Comment by sebastian-meyer** [comment]
I prefer @BFallert's proposed solution since it retains the option to show the fulltext inline.

**Comment by wrznr** [comment]
Indeed, it would be great if it was that simple. Thanks @BFallert. Just to make sure: I was referring to the typographic alignment of the original source (and not just an optimized view).

**Comment by BFallert** [comment]
Yes @wrznr, its no optimized view! 
You can see an example at [http://digi.bib.uni-mannheim.de/urn/urn:nbn:de:bsz:180-digad-30004](http://digi.bib.uni-mannheim.de/urn/urn:nbn:de:bsz:180-digad-30004)

**Comment by wrznr** [comment]
Perfect. No change required.

**Comment by bertsky** [comment]
@sebastian-meyer @BFallert great to know this is only a matter of configuration. But then why is DFG Viewer not set up like this? [Your example](https://dfg-viewer.de/show/?tx_dlf%5Bid%5D=https%3a%2f%2fdigi.bib.uni-mannheim.de%2foai%2f%3fverb%3dGetRecord%26metadataPrefix%3dmets%26identifier%3d490431607) does not work there. Also, SLUB's [Digitale Sammlungen](https://digital.slub-dresden.de/werkansicht/dlf/311282/148#) is not configured like this.

**Comment by bertsky** [comment]
Is [this](https://github.com/slub/dfg-viewer/blob/c832c5e87fd874c7ec802e1c3881970eed47959f/Resources/Private/Less/modules/fulltext.less#L36-L63) where I should expect the change, or some install-time configuration file?

**Comment by BFallert** [comment]
The div class/id has changed in the new versions of kitodo.presentation, you 
have to add the new version to the old one `#tx-dlf-fulltextselection span.textline`
or replace the old one with this one  `.fulltext-container span.textline`

works in both versions:

    .fulltext-container span.textline,
    #tx-dlf-fulltextselection span.textline {
        display: block;
    }

I am not a part of the DFG-Viewer-Team and as well not of the SLUB, i don't know the reason for there implementation.

**Comment by BFallert** [comment]
In principle, this is the right place. 
But a Less file must still be converted into a css file, i.e. it cannot be used directly. For this process exists in Build directory a Gruntfile.js. 

see eventually [https://gruntjs.com/getting-started](https://gruntjs.com/getting-started)
