### ISSUE TITLE
Migrate documentation for TYPO3 v8.7.8+

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#355]
See https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html

**Comment by albig** [comment]
Step 1+3 are already done.
Step 2 would be done with PR #366 
Step 4 has to be done manually after next release.

**Comment by sebastian-meyer** [comment]
Step 4 is done as well: https://github.com/TYPO3-Documentation/T3DocTeam/issues/92#issuecomment-532102363
