### ISSUE TITLE
Plugin Template selection fails for tools of toolbox.

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#363]
Each tool of the toolbox has it's own template. The getTemplate() method of the abstractPlugin class checks for a configuration `templateFile` which is always the toolbox itself but never the desired tool.

Proposal (pull request follows): Use one template file ("toolbox.tmpl") with several markers for each tool. Select the right marker inside the tool by calling `getTemplate('###MARKER###').`

**Comment by sebastian-meyer** [comment]
The idea was to be able to provide additional tools in separate extension simply by registering them in the extension's `ext_localconf.php`:
https://github.com/kitodo/kitodo-presentation/blob/fcd78b6b9bb4ac3b0fd6cbf0c916e5433b8774e3/ext_localconf.php#L48
But this requires to have separate templates for every tool as well.

**Comment by sebastian-meyer** [comment]
Instead of merging all templates together we should fix the template resolving in `getTemplate()`. This must have worked in the past, because otherwise no tool would have generated any output...

**Comment by albig** [comment]
getTemplate was never used inside the tools. Because it doesn't work ;-)

Am 29.07.19 um 16:43 schrieb Sebastian Meyer:
>
> Instead of merging all templates together we should fix the template
> resolving in |getTemplate()|. This must have worked in the past,
> because otherwise no tool would have generated any output...
>

**Comment by sebastian-meyer** [comment]
Hm, I don't see why though.

Here we instanciate a new `cObj` for every tool:
https://github.com/kitodo/kitodo-presentation/blob/fcd78b6b9bb4ac3b0fd6cbf0c916e5433b8774e3/Classes/Plugin/Toolbox.php#L54-L55

For those `cObj` we then call `getTemplate()`:
https://github.com/kitodo/kitodo-presentation/blob/fcd78b6b9bb4ac3b0fd6cbf0c916e5433b8774e3/Classes/Plugin/Tools/ImageManipulationTool.php#L42

Which looks at `$this->conf` for the configured template file:
https://github.com/kitodo/kitodo-presentation/blob/fcd78b6b9bb4ac3b0fd6cbf0c916e5433b8774e3/Classes/Common/AbstractPlugin.php#L57

`$this->conf` is inherited from the parent `cObj` of the toolbox itself:
https://github.com/kitodo/kitodo-presentation/blob/fcd78b6b9bb4ac3b0fd6cbf0c916e5433b8774e3/Classes/Plugin/Toolbox.php#L44-L47

But then gets merged with the configuration of the tool:
https://github.com/kitodo/kitodo-presentation/blob/fcd78b6b9bb4ac3b0fd6cbf0c916e5433b8774e3/Classes/Plugin/Tools/ImageManipulationTool.php#L40

I suspect the problem there. For some reason the configuration of the tool doesn't take precedence over the configuration of the toolbox.

**Comment by albig** [comment]
It's broken since 919ee33. This remove the `$this->conf['toolTemplateFile'] `configuration.

**Comment by sebastian-meyer** [comment]
Ah, well. So the configuration option just got renamed. If you set the template file as `plugin.ImageManipulationTool.templateFile` instead of `plugin.ImageManipulationTool.toolTemplateFile` it should work as expected.

**Comment by albig** [comment]
Unfortunately, it doesn't as `templateFile` is set by the toolbox and the configuration is merged. So getTemplate() find's the configuration of `templateFile` and returns the template of the toolbox. `toolTemplateFile` is never used.

I would like to use the tools without all this toolbox stuff. This would be great.

**Comment by sebastian-meyer** [comment]
Yes, maybe we should turn all the tools into proper plugins.

**Comment by christopher-timm** [comment]
I am working on a redesign project by the SUB Hamburg and this bug blocks the completion of the detail view. Because of that I discussed with @sebastian-meyer  that we would implement a workaround. So the toolbox would be again usable with a custom template.
