### ISSUE TITLE
Pageview JavaScript breaks with MSIE 11

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#410]
The pageview plugin brings new JavaScript for the annotation feature of - currently only - IIIF manifests.

Unfortunately this JavaScript uses ES6 features which [are not supported by MSIE 11](http://kangax.github.io/compat-table/es6/). As MSIE 11 is still used (_my deepest sympathy to the users who cannot change_), we should find a workaround to support basic pageview functionality.

Suggestion: Do not add the Annotation-JavaScript code in case of non-IIIF manifests like ordinary METS-documents.

**Comment by sebastian-meyer** [comment]
Fixed by #411

**Comment by sebastian-meyer** [comment]
Maybe we should revert #411 then? #412 seems to be a better fix for this issue.

**Comment by lutzhelm** [comment]
#411 does not do any harm. Annotations will probably not be a thing for METS documents in the near future.

**Comment by lutzhelm** [comment]
#411 should not do any harm. Code referring to `DlfAnnotationControl` will only be executed if annotations are available, and it is unlikely to be the case for METS in the near future.
