### ISSUE TITLE
OAI PMH plugin does not support POST method

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#46]
Extract from the OAI PMH Protocol Version 2.0:

```
3.1.1 HTTP Request Format

OAI-PMH requests must be submitted using either the HTTP GET or POST methods.
POST has the advantage of imposing no limitations on the length of arguments.
Repositories must support both the GET and POST methods.
```

Goobi.Presentation currently fails to support POST methods.
This was detected and reported as an error by the BASE OAI-PMH Validator (http://oval.base-search.net/).

**Comment by sebastian-meyer** [comment]
Hm, Goobi uses `t3lib_div::_GP()`, so in theory it should support GET and POST. I'll look into it.

**Comment by stweil** [comment]
IMHO, this bug has low priority because obviously typically only GET methods are used.
Our server only got POST requests from the validator.

**Comment by sebastian-meyer** [comment]
OK. I'll postpone it until a later release then.

**Comment by stweil** [comment]
The BASE OAI-PMH Validator reports "Server accepts only GET requests" if the OAI-PMH  URL does not end with a slash:

http://digital.slub-dresden.de/oai  - error reported
http://digital.slub-dresden.de/oai/ - no error, GET and POST work

GET and POST to the first URL gets a 301 return code (Moved Permanently). The validator then automatically uses the second URL for GET, but fails for POST.

This looks like a problem of the validator which interprets the "Moved Permanently" status in one case (GET) but ignores it for the other case (PUT).

**Comment by sebastian-meyer** [comment]
Ah, thanks for the investigation and clarification! I wouldn't have catched that!
