### ISSUE TITLE
SQL-Error within method makeFacetsMenuArray() of class Search on empty facetCollections

### ISSUE THREAD

**Issue by frank-ulrich-weber** [kitodo/kitodo-presentation#469]
## Description

If there ist no "collection as facet" is selected (facetCollection) in the backend of the search plugin, an empty and invalid IN statement is created within method make FacetsMenuArray() of class Search. 

## Reproduction

see Description

## Expected Behavior

If there is no collection as facet is selected the IN statement could be skipped I think.

Replace line 606
$queryBuilder->expr()->in('tx_dlf_collections.uid', $facetCollections),
with
!empty($facetCollections) ? $queryBuilder->expr()->in('tx_dlf_collections.uid', $facetCollections) : '',

## Screenshots and Examples

Uncaught TYPO3 Exception
An exception occurred while executing 'SELECT `tx_dlf_collections`.`index_name` AS `index_name` FROM `tx_dlf_collections` WHERE (`tx_dlf_collections`.`uid` IN ()) AND ((`tx_dlf_collections`.`deleted` = 0) AND (`tx_dlf_collections`.`hidden` = 0) AND (((`tx_dlf_collections`.`fe_group` = '') OR (`tx_dlf_collections`.`fe_group` IS NULL) OR (`tx_dlf_collections`.`fe_group` = '0') OR (FIND_IN_SET('0', `tx_dlf_collections`.`fe_group`)) OR (FIND_IN_SET('-1', `tx_dlf_collections`.`fe_group`))))) AND ((`tx_dlf_collections`.`deleted` = 0) AND (`tx_dlf_collections`.`hidden` = 0))': You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')) AND ((`tx_dlf_collections`.`deleted` = 0) AND (`tx_dlf_collections`.`hidden` ' at line 1

Doctrine\DBAL\Exception\SyntaxErrorException thrown in file
C:\zeutschel\programme\typo3_src-8.7.30\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php in line 90.

## Environment

 - OS version: Windows 10
 - RDBMS version: MySQL 5.7.20
 - Apache Solr version: 7.4
 - TYPO3 version: [e.g. 8.7.29]
 - PHP version: 8.7.30

**Comment by sebastian-meyer** [comment]
Fixed with #473
