### ISSUE TITLE
Functionality of method hasNoFormatForDocument() of class ext_update

### ISSUE THREAD

**Issue by frank-ulrich-weber** [kitodo/kitodo-presentation#472]
Within the extension update functionality the method hasNoFormatForDocument() checks wether the Column "document_format" of table "tx_dlf_document" exists. Only if the column does not exist updateDocumentAddFormat() is called. But I think the column is allways automatically added when updating the extension and the function is never called. Wouldn't it be better to set the default to METS if the column is empty for all entries or by ext_tables.sql?

**Comment by sebastian-meyer** [comment]
Yes, you are right. `hasNoFormatForDocument()` should check for non-existing **or empty** column `document_format`. `updateDocumentAddFormat()` should add the column and/or set it to `METS` respectively.
Could you provide a bugfix, please?

**Comment by sebastian-meyer** [comment]
Nevermind, I'll provide a bugfix myself... 😄
