### ISSUE TITLE
Language overlay of collection does not work.

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#474]
## Description

The language overlay of the collection plugin does not work. The default language is shown instead.

## Reproduction

1. Make a translation of your data-folder (required to get the "translation" button visible).
2. Translate a collection record (description and label fields)
3. Call the collection plugin (list or single collection) and change the website language

## Environment

 - OS version: [Debian Linux 10]
 - TYPO3 version: [8.7.29, 9.5.13]
 - PHP version: [7.3]

**Comment by sebastian-meyer** [comment]
Fixed with #475
