### ISSUE TITLE
SQL Error in class.ext_update.php

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#49]
The following error is thrown in class.ext_update.php:

<pre>
ERROR: Unknown column 'tx_dlf_metadata.xpath' in 'where clause'
</pre>

The field 'xpath' doesn't exists. @sebastian-meyer: can we just remove this part of the query?

Background: This query is called on every access of the Extension Manager as of TYOPO3 6.2.12. The EM checks if the available update scripts have some update tasks to do. If not, the update icon is not shown.

**Comment by sebastian-meyer** [comment]
The field `tx_dlf_metada.xpath` existed in earlier versions (< 1.2) of Goobi.Presentation. It has to be migrated when updating from such a version, that's why the update script checks the existence of the field.
