### ISSUE TITLE
Current master is broken (missing OpenLayers dependency)

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#52]
Page views with zoom don't work: neither the controls for zooming nor the page image are shown.

The Firefox web developer console shows these errors:

TypeError: P is undefined Class.js:64:3
TypeError: OpenLayers.Control.ZoomIn is not a constructor ZoomPanel.js:47:12

ZoomIn.js depends on  Button.js which is missing.

**Comment by sebastian-meyer** [comment]
Bug fix merged (#53). Thanks!
