### ISSUE TITLE
PageViewProxy is slow with redirects due to bug in Guzzle library.

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#540]
## Description

On every pageview, the `PageViewProxy` is used to check the HTTP header of the images to be shown. This is done to check the CORS headers before offering certain features like the imagemanipulation tool.

Behind the scene this is done by fetching from server side only the HTTP header using the TYPO3 core function `GeneralUtility::getUrl()`. This function uses in TYPO3 9.5.20 the [Guzzle HTTP library](https://github.com/guzzle/guzzle/) in version 6.5.5.

If the image url is redirected, the redirection will be followed by default settings. But the [Guzzle HTTP library](https://github.com/guzzle/guzzle/) switches the request method from HEAD to GET on redirection! Now the full image will be downloaded and this may be slow depending on the data provider. 

I've seen data provider with images > 35MB which needed 220 seconds for download. So we need in this case 220 seconds just to get the information if CORS-headers are present or not. This is of course unusable.

The people from Guzzle accepted (https://github.com/guzzle/guzzle/issues/2046) this as an bug and a fix (https://github.com/guzzle/guzzle/pull/2047/) is in master but in no release yet.

This is actually no Kitodo.Presentation or DFG-Viewer bug. But we should keep an eye on it.

## Expected Behavior

The redirect should be followed on keeping the request method (HEAD in this case).

## Environment

 - OS version: Debian Linux 10
 - TYPO3 version: 9.5.20
 - Guzzle HTTP library: 6.5.5

## Additional Context

In the running DFG-Viewer (https://dfg-viewer.de/) with current Kitodo.Presentation, I patched the Guzzle HTTP library with the mentioned patch.

**Comment by sebastian-meyer** [comment]
The mentioned fix is part of [Milestone 7.1.0](https://github.com/guzzle/guzzle/milestone/10?closed=1) which according to [TYPO3 9.5's composer.json](https://github.com/TYPO3/TYPO3.CMS/blob/d2650bff9ff2ee00b6b769886c167124d48e181a/composer.json#L45) unfortunately isn't compatible with TYPO3 9.5 (`^6.3.0`). We could try upgrading anyway or keep using the patch.

**Comment by albig** [comment]
Either we implement different way or we have to wait for TYPO3 11 LTS. Even TYPO3 10 LTS keeps on using Guzzle `^6.3.0`.

The whole idea behind prefetching the image header is not perfect. Maybe we should inspect if using [CORS preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) is the better approach.

**Comment by dvoracek-slub** [comment]
May this be closed? Since #758 we don't send a separate HEAD request anymore.

**Comment by albig** [comment]
Fixed in #758
