### ISSUE TITLE
[Feature Request] Get thumbnail images from image server

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#547]
### Problem

Kitodo.Presentation currently does not show thumbnail images if no corresponding fileGrp  exists in the METS file,
even if there is a DEFAULT fileGrp with image server URLs which would allow getting thumbnail images.

### Proposed Solution

Kitodo.Presentation could use the image server URLs to get thumbnail images of the required small size.

## Target Version

The feature could be added to any supported release (which all support image servers).

**Comment by stweil** [comment]
Should this request be tagged with "development fund"?

**Comment by sebastian-meyer** [comment]
I added the tag to #601, because that issue contains a bit more information.
