### ISSUE TITLE
Collection plugin does not list all volumes with same publication date

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#559]
## Description

Two volumes overwrite each other in the listview of a single collection if the `volume_sorting` field is equal.

## Reproduction

Index two volumes with same `volume_sorting` value.

## Expected Behavior

Volumes of multivolume works get the `volume_sorting` field set in the database to the publication date.

### Document 1
```
<mods:originInfo eventType="publication">
  <mods:dateIssued keyDate="yes">[1887-1900]</mods:dateIssued>
  <mods:dateOther encoding="w3cdtf" type="order">1900</mods:dateOther>
</mods:originInfo>
```
### Document 2
```
<mods:originInfo eventType="publication">
  <mods:dateIssued keyDate="yes">[circa 1900]</mods:dateIssued>
  <mods:dateOther encoding="w3cdtf" type="order">1900</mods:dateOther>
</mods:originInfo>
```
Both documents have `volume_sorting=1900` after indexing.

The code in `Collection::showSingleCollection()` [Line 402](https://github.com/kitodo/kitodo-presentation/blob/master/Classes/Plugin/Collection.php#L402) assumes the `volume_sorting` field to be unique which is not the case.

## Question

Does this make sense? Why is the ORDER-Label in the structMap type="LOGICAL" ignored for this purpose? Shouldn't this be changed in the document class?

## Screenshots and Examples

Example files:

https://digital.slub-dresden.de/data/kitodo/Dien_1683659783_0008/Dien_1683659783_0008_mets.xml
https://digital.slub-dresden.de/data/kitodo/Dien_1683658167_0006/Dien_1683658167_0006_mets.xml

## Environment

 - Kitodo.Presentation 3.1.2

**Comment by andre-hohmann** [comment]
I agree that the ORDER-Label in the structMap type="LOGICAL" should be used for the sorting in the lists. 

The value is captured intellectually in `<mods:part order="XXX" type="host"/>`, to ensure the correct order, even when the volumes have to be sorted by title or other criteria.

**Comment by albig** [comment]
The same happens with periodical media like newspaper.

```
type:newspaper (anchor)
  | -> type:year 1 with `volume_sorting == ''`
  | -> type:year 2 with `volume_sorting == ''`
  | -> type:year 3 with `volume_sorting == ''`
 ```
The result in Collection -> Listview is 
```
type:newspaper (anchor)
  | -> type:year 3
 ```
We could fix this in case of newspapers easily by adding the orderlabel to the array key in showSingleCollection():

```
$subparts[$resArray['partof']][$resArray['volume_sorting'] . '-' . $resArray['orderlabel']] = [
 'u' => $resArray['uid'],
 'h' => '',
 's' => $sorting,
 'p' => []
];
```
But this doesn't fix the other case.
