### ISSUE TITLE
Fulltext switch doesn't work as expected

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#570]
@albig reports:

Sorry, I cannot reproduce what this setting does:

* Without launchState: nothing happens. Ok.
* with launchState=off: the fulltext is shown initially and on every click on the button it is marked once more. So the color gets darker and darker (in the screenshot its getting more and more red)
* with launchState=on: the old behaviour shows up

So what is launchState=off good for?
![fulltext-launchstate](https://user-images.githubusercontent.com/3354500/102941310-b2d36d00-44b2-11eb-96d2-25a265a4f321.png)

_Originally posted by @albig in https://github.com/kitodo/kitodo-presentation/pull/563#discussion_r547549674_

**Comment by sebastian-meyer** [comment]
This is how it should work:

* If `launchState = off` everything should behave as before: The fulltext isn't shown until you click the link/button. This should be the default behavior as well for backwards compatibility.
* If `launchState = on` the fulltext is shown when loading the page, without having to click a link/button first. It can be turned off by clicking the link/button.

(For the Zeitungsportal, we would set `launchState = on` and hide the link to switch it off via CSS.)

**Comment by beatrycze-volk** [comment]
I'm suprised that 'Volltext' text is still changing something when `off`. I will now make it now plain text and write default `on`.

In fact it is opposite. `on` for clickable and `off` for always visible.
'To meet the requirements of the Zeitungsportal, we would set plugin.tx_dlf`_fulltexttool.launchState = off` and hide the off-switch via CSS.' - https://github.com/kitodo/kitodo-presentation/pull/563
