### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#59]
This TYPO3 extension should include an OpenOffice manual.

Otherwise TYPO3 extension manager / Get Extensions / (filter dlf) / Show all versions of dlf / Manual Read online fails with this dead link: http://docs.typo3.org/typo3cms/extensions/dlf/

Maybe it is sufficient to add a rudimentary dlf/doc/manual.sxw which refers to the available websites.

**Comment by albig** [comment]
You describe a bug in the extension manager. The typo3.org website knows how to handle extension with missing documentation.

But of course, a placeholder documentation would be better anyway.

The manual.sxw is not the prefered way for extensions documentation anymore. 

The better format is a ReST documentation in EXT:dlf/Documentation/

http://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/Documentation/Index.html

If either doc/manual.sxw or Documentation/ exist, the extension manual get's rendered automatically.

**Comment by stweil** [comment]
Thanks for the hint to the new documentation format.

Here is a very preliminary version of a Sphinx project for Goobi.Presentation:
https://github.com/stweil/goobi-presentation/tree/documentation

Comments and suggestions for improvements are welcome.
Of course you may also pull it as it is, so it can be updated incrementally by pull requests.

**Comment by albig** [comment]
Perfect! Thank you.
