### ISSUE TITLE
Latest tagged version v1.3.0 cannot be used with current TYPO3

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#60]
Several fixes which are needed for TYPO3 6.2 are missing in v1.3.0.
We should have a working version in the TYPO3 extension repository.

**Comment by sebastian-meyer** [comment]
The 1.3.1 release should be compatible with the current TYPO3 version, but there is still one bug (#46) open. We could postpone the bug for a later release. What do you think?

**Comment by stweil** [comment]
As this is not a new bug, I'd postpone it and release 1.3.1 as it is.
