### ISSUE TITLE
Move JavaScript from plugin code to TypoScript

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#606]
## Description

Currently, three plugins add JavaScript to the website:
* Pageview
* AudioPlayer
* Search

Usually this is done by adding the files to the footer with Pagerenderer::addJsFooterFile().

In case of the Pageview and AudioPlayer plugins, it is possible to add all JavaScript to a marker inside the plugin section of the website body.

### Problem

This behavior makes it impossible to overwrite or exclude some JavaScript files or to influence the position (head or footer) of the included JavaScript files.

### Proposed Solution

The JavaScript files should be added by [TypoScript](https://docs.typo3.org/m/typo3/reference-typoscript/master/en-us/Setup/Page/Index.html#includejs-array). A basis TypoScript-Template is already part of Kitodo.Presentation and provides jQuery. This could be extended or a new one can be added.

The integrator now has the possibility to take this configuration or to discard it and uses the flexibility of TypoScript.

In case of the Pageview plugin, the dynamic JavaScript inline code must stay in the plugin. For this, the feature of the template marker may be preserved.

## Target Version

master

**Comment by sebastian-meyer** [comment]
If I remember correctly we changed this explicitly for the Zeitungsportal. I am fine with the proposed reversal, but we should keep in mind that this probably has an impact on the Zeitungsportal and needs some workaround there.

**Comment by beatrycze-volk** [comment]
Actually it is also now a change for Zeitungsportal. It was necessary as previous solution was not satisfying anymore requirements.

**Comment by sebastian-meyer** [comment]
Just for reference: The last change was in #507

**Comment by albig** [comment]
Closed by #607
