### ISSUE TITLE
Wrong table name "tx_documents" in getDocumentType 

### ISSUE THREAD

**Issue by hnesk** [kitodo/kitodo-presentation#675]
https://github.com/kitodo/kitodo-presentation/blob/cd5414fe083bbd21e9d935cfda67445b2ce5219e/Classes/ExpressionLanguage/DocumentTypeFunctionProvider.php#L131

This line should read: 
Helper::whereExpression('tx_dlf_documents')

**Comment by albig** [comment]
That's true. Could you provide a patch?
