### ISSUE TITLE
Zoom slider doesn't work as intended

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#74]
Currently the zoom slider works only if the zoom is changed step by step. If you move the slider back and forth multiple times, the results are erratic and not as expected.

**Comment by albig** [comment]
With Kitodo.Presentation 2.0 it got even worse: If you click the slider bar anywhere, the main image disappears and won't come back in the current browser session. Not on an other page and even not in any other document.

The reason for this seems to be the session cookies
- tx-dlf-pageview-centerLat
- tx-dlf-pageview-centerLat

which get "undefined" after this event.

Deleting these Cookies doesn't help! Only closing the browser brings back the image(s).
