### ISSUE TITLE
Using ke_search in place of Solr

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-presentation#762]
One of our hosters, being a Typo3 developer himself, suggested using the ke_search / ke_search_premium extensions for Kitodo.Presentation. This eliminates the need to maintain your own Solr.

Examples of websites that are based on this extension are these:

- https://www.medizin-zentrum-dortmund.de/de/suche/
- https://www.autobahn.de/suche

I would like to pass this suggestion on here and put it up for discussion.

**Comment by albig** [comment]
This would be a huge refactoring with unkown result.

The Solr in Kitodo.Presentation is not only used for metadata search. This could be done in the database and here `EXT:ke_search` could come into play. The more complexe part is the full text search. Here we just introduced a Solr plugin to get word coordinates in search results. As we decided to make Solr required some years ago, other plugins depends on it now.

I think your hoster expert does only know "simple" website search. For this `EXT:ke_search` is a fast and reliable replacement for the complex `EXT:solr` + Solr combination.

Luckily, Solr is quite simple to maintain - if you know few critical points.
