### ISSUE TITLE
Add support for TYPO3 7 LTS

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#77]
The current version of TYPO3 is 7 LTS. It is recommended for new projects and will get security updates until November 2018.

The current Goobi.Presentation supports TYPO3 6.2 LTS which gets maintenance until March 2017. According to dlf/ext_emconf.php, the exact range of versions supported by Goobi.Presentation is from 4.5.0 up to 6.2.99.

As all TYPO3 versions before TYPO3 6.2 LTS are completely unsupported, I suggest dropping support for those versions in the next version of Goobi.Presentation, too. This includes TYPO3 4.5 LTS, 6.0, 6.1 and others.

Goobi.Presentation currently fails to work with TYPO3 7 LTS because some deprecated interfaces were removed (maybe there are more reasons). There is an extension "compatibility6" which provides some backwards-compatibility, but I don't know whether it is sufficient for Goobi.Presentation, and people suggest not to use it because it is bad for the performance of TYPO3. Therefore code changes for Goobi.Presentation are needed to fully support TYPO3 7 LTS. These changes will be much easier if we can drop support for anything before TYPO3 6.2 LTS.

**Comment by sebastian-meyer** [comment]
I will drop support for anything before TYPO3 6.2 LTS with the next major release of Goobi.Presentation (2.0), which is coming soon.

The changes for compatibility with TYPO3 7, however, are not yet planned for the next release.

**Comment by stweil** [comment]
The changes needed for TYPO3 7 are in interfaces which were already deprecated for 6.2, so it might be a good idea to have them in the next release. I'll start sending pull requests, and we'll see whether we can reach TYPO3 7 compatibility in time.

**Comment by stweil** [comment]
Most of the deprecated interfaces are fixed now (#96 should be the last pull request for this). There is also an incompatible change in class \TYPO3\CMS\Core\Messaging\FlashMessageQueue which is addressed in pull request #97. In addition, the range of supported TYPO3 versions in dlf/ext_emconf.php must be updated (pull request will follow). According to some notes on the web, there were also incompatible changes in \TYPO3\CMS\Backend\Template\DocumentTemplate which might affect our code (tests to be done). After these changes, Goobi.Presentation seems to be usable with TYPO3 7.6.2.

More changes are needed to fix new deprecations which were introduced in TYPO3 7.0. Those changes will be needed for TYPO3 8.0.

**Comment by sebastian-meyer** [comment]
All changes should be merged now. Thanks to @stweil for the contributions!
