### ISSUE TITLE
Suspicion of memory leak in kitodo:reindex CLI job

### ISSUE THREAD

**Issue by albig** [kitodo/kitodo-presentation#822]
## Description

Using the `kitodo:reindex` cli job with many documents rise the memory usage linear. The process get's killed after ~1000 documents per 4GB RAM.

## Expected Behavior

We had this problem in former times but fixed it. This will be new with the implementation in Kitodo.Presentation 4.0.

## Screenshots and Examples

Example reindexing  1254 out of 18074 documents.  The process is killed, because not enough memory could be allocated.

![memory-pinpoint=1655926916,1655933531](https://user-images.githubusercontent.com/3354500/175136988-444efd80-d057-4d80-8c98-40e66b0cbe01.png)

## Environment

 - OS version: Debian 11
 - TYPO3 version: 10.4
 - PHP version: 7.4
 - Kitodo.Presentation 4.0.1

**Comment by sebastian-meyer** [comment]
In 3.x we cleared the document registry after indexing:
https://github.com/kitodo/kitodo-presentation/blob/4a20621afc30778ba3b045be5110353cf4fd4fd4/Classes/Command/ReindexCommand.php#L181-L182
That way the registry never holds more than one document instance.

In 4.x this is missing, so the registry grows bigger with every additional document that is instanced for indexing.

I'll provide a fix.
