### ISSUE TITLE
Updates needed for recent versions of Solr to fix warnings (index-time boosts no longer supported)

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-presentation#860]
## Description

An installation of latest Kitodo.Presentation (git master) with a recent solr 8.11.2 shows several Solr warnings.

## Reproduction

Steps to reproduce the behaviour:

1. Install Kitodo.Presentation (git master) with a recent Solr 8.11.2
2. Open the Solr logging in a web browser (http://localhost:8983/solr/#/~logging)

## Current warnings

```
9.10.2022, 15:44:52 | WARN false | x:dlfCore0 | SolrConfig | solrconfig.xml: <jmx> is no longer supported,&#8203; use solr.xml:/metrics/reporter section instead
12.10.2022, 10:10:07 | WARN true | x:dlfCore0 | XMLLoader | Ignoring field boost: 1 as index-time boosts are not supported anymore
```

**Comment by stweil** [comment]
Related: #396, #454.

**Comment by sebastian-meyer** [comment]
Closing this as duplicate. The issue is adressed in the current Kitodo development fund (see #1120 and #1122).
