### ISSUE TITLE
Link in administrator documentation is wrong

### ISSUE THREAD

**Issue by BFallert** [kitodo/kitodo-presentation#891]
## Description

The link in the the file `https://github.com/kitodo/kitodo-presentation/blob/master/Documentation/Administrator/Index.rst` for (MiniOCR) is wrong.

`Please note: The full text is stored in Solr index in a XML format ([MiniOCR](https://dbmdz.github.io/solr-ocrhighlighting/formats/#miniocr)). This will rise the demand for storage space. You should therefore monitor the disc usage during reindexing.`

## Reproduction

Steps to reproduce the behaviour:

1. Go to [https://docs.typo3.org/p/kitodo/presentation/4.0/en-us/Administrator/Index.html#version-3-2-3-3](https://docs.typo3.org/p/kitodo/presentation/4.0/en-us/Administrator/Index.html#version-3-2-3-3)
2. Click on [MiniOCR](https://dbmdz.github.io/solr-ocrhighlighting/formats/#miniocr) in the section 
`Please note: The full text is stored in Solr index in a XML format ([MiniOCR](https://dbmdz.github.io/solr-ocrhighlighting/formats/#miniocr)). This will rise the demand for storage space. You should therefore monitor the disc usage during reindexing.` 
3. See error

## Cause

Link destination was changed (**formats/#miniocr** no longer exists), not sure if [https://dbmdz.github.io/solr-ocrhighlighting/0.8.3/](https://dbmdz.github.io/solr-ocrhighlighting/0.8.3/) is correct?

**Comment by sebastian-meyer** [comment]
Since I had to update documentation anyway because of code changes that require at least version 0.8.0 of the solr_ocrhighlighting plugin, I changed this as well. Thanks for the hint!

[Commit ](https://github.com/kitodo/kitodo-presentation/commit/acfdfe969742e332974b4f62c06a20a56d2e1d8f)
