### ISSUE TITLE
Fix security issues and warnings (and improve code styling)

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-presentation#893]
## Description

We are using some industry-standard static code analyzers for code and security scanning like Dependabot, CodeQL and Codacy. Those tools produced a lot of warnings of different severities from "Note" to "High".

This proposal's goal is to fix at least all **security related issues**. Those are currently:
* [0 critical security issues](https://github.com/kitodo/kitodo-presentation/security/code-scanning?query=is%3Aopen+branch%3Amaster+severity%3Acritical)
* [1 high security issue](https://github.com/kitodo/kitodo-presentation/security/code-scanning?query=is%3Aopen+branch%3Amaster+severity%3Ahigh)
* [2 medium security issues](https://github.com/kitodo/kitodo-presentation/security/code-scanning?query=is%3Aopen+branch%3Amaster+severity%3Amedium)
* [0 low security issues](https://github.com/kitodo/kitodo-presentation/security/code-scanning?query=is%3Aopen+branch%3Amaster+severity%3Alow)

Furthermore there are a lot of **code-style related issues**. The issues with severity "Warning" or higher should at least be assessed and fixed if this can be done with reasonable effort (most of them are duplicates, i. e. multiple occurences of the same issue). Those are currently:
* [0 errors](https://github.com/kitodo/kitodo-presentation/security/code-scanning?query=is%3Aopen+branch%3Amaster+severity%3Aerror)
* [155 warnings](https://github.com/kitodo/kitodo-presentation/security/code-scanning?query=is%3Aopen+branch%3Amaster+severity%3Awarning)
* [222 notes](https://github.com/kitodo/kitodo-presentation/security/code-scanning?query=is%3Aopen+branch%3Amaster+severity%3Anote)

## Related Issues

The security alerts can be found [on the security tab](https://github.com/kitodo/kitodo-presentation/security/code-scanning).

## Expected Benefits of this Development

This proposal would make Kitodo.Presentation more stable and secure. It would also eliminate the abundance of security messages, making it easier to identify new problems as they arise.

## Estimated Costs and Complexity

The complexity is medium and the cost are low (2-3 days).

**Comment by stweil** [comment]
Only "members" of the Kitodo organization or the repository can see the security related pages which are mentioned above. I was member in 2017, but obviously removed later.

**Comment by sebastian-meyer** [comment]
Access can only be granted to admins, members with push rights and specific user groups. I'd have to create a user group and add all current outside collaborators to that group... :o(

**Comment by stweil** [comment]
It's not a real problem for me personally, because my fork runs the same security checks and reports them (so the whole GitHub concept of hiding the security reports is strange and wasting energy for unnecessary computations).

**Comment by sebastian-meyer** [comment]
Votes: 11

**Comment by frank-ulrich-weber** [comment]
Can you please give me access to the security tab to fix the issues and warnings? Thanks!

**Comment by stweil** [comment]
It's usually sufficient to fork the repository and use the security tab in your own fork (see my comment above). Then you can either use the fixes which are generated by CodeQL or manual fixes to create a pull request.

**Comment by sebastian-meyer** [comment]
> Can you please give me access to the security tab to fix the issues and warnings? Thanks!

I've granted you the security manager role. You should be able to access the security tab now.

**Comment by frank-ulrich-weber** [comment]
Thanks Stefan and Sebastian, that helps a lot!

**Comment by frank-ulrich-weber** [comment]
I think I'm blind, but now I see 40 security issues on my current fork of the kitodo-presentation master: What do I have to do/configure to see the same amount of issues? How can I apply the same checks on a branch? I think I yust need a hint... Thanks!

**Comment by sebastian-meyer** [comment]
- [x] #1032
- [x] #1037 
- [x] #1038 
- [x] #1041 
- [x] #1043 
- [x] #1044 
- [x] #1048 
- [x] #1049 
- [x] #1058

**Comment by stweil** [comment]
GitHub code scanning currently reports 7 warnings and more than 6000 notes for the master branch.

**Comment by sebastian-meyer** [comment]
I don't see any notes and of the warnings we decided to ignore all that are reported for the 3D viewer javascripts (because those are still in a prototypical state and under heavy development). I've forwarded them to the developers and they will take care of those.
So, for me this looks fine, now.

**Comment by stweil** [comment]
> I don't see any notes

Then go to settings/security_analysis and look for "Code scanning" and "Protection rules". There you can set the alert severity levels. Set both levels to "any" to get all the notes, too. Not all kinds of notes are useful, but some of them are.
