### ISSUE TITLE
[BUG] Missing option in the backend of the "Navigation" plugin to insert the "Jump to last page" button.

### ISSUE THREAD

**Issue by BFallert** [kitodo/kitodo-presentation#915]
## Description

In the template [Resources/Private/Templates/Navigation/Main.html](https://github.com/kitodo/kitodo-presentation/blob/master/Resources/Private/Templates/Navigation/Main.html) there is a setting to insert a link to jump to the last page
Line 178: `<f:section name="render.pageLast">`

This setting is also mentioned in the documentation, see [Documentation/Plugins/Index.rst#navigation](https://github.com/kitodo/kitodo-presentation/blob/master/Documentation/Plugins/Index.rst#navigation)
```
  - :Property:
        features
    :Data Type:
        :ref:'t3tsref:data-type-string'
    :Default:
       By default all features are activated. The selection is stored as comma separated list.

        doublepage,pageFirst,pageBack,pageStepBack,pageselect,pageForward,pageStepForward,pageLast,listview,zoom,rotation
``` 

## Reproduction

Steps to reproduce the behaviour:

1. with a installed kitodo.presentation insert a side content element with the "Kitodo Plugin" "Kitodo: Navigation"
2. Click on "Plugin" tab

## Expected Behavior

There should be an item "Last Page" in the list under "Available Items".

## Screenshots and Examples

![image](https://user-images.githubusercontent.com/4037984/220866768-663d0d3f-cf2e-4597-b77c-b25647611afc.png)

## Environment

 - OS version: Debian Linux 11
 - RDBMS version: MariaDB 10.5.18-MariaDB-0+deb11u1 Debian 11
 - Apache Solr version: solr-8.11.2
 - TYPO3 version: 10.4.36
 - PHP version: 7.4.33

## Additional Context

The function is activated in the settings

```
 plugin.tx_dlf_navigation {
     settings {
         pageStep = 10
         features = doublepage,pageFirst,pageBack,pageStepBack,pageselect,pageForward,pageStepForward,pageLast,listview,zoom,rotation
     }
 }
```

**Comment by stweil** [comment]
Is this a bug? Or a missing feature which could be addressed by the development fund?
