### ISSUE TITLE
Safari-Browser does not display JPEG-images with (exotic) embedded color profiles

### ISSUE THREAD

**Issue by mahaesin** [kitodo/kitodo-presentation#925]
We encountered a strange rendering problem of page images that have an embedded icc color profile using Safari browser on current Apple devices running macOS or iOS.

TIF-Images from our Zeutschel OS15000 scanner have an embedded icc color profile ("OS15000_mG_CE"). In our current workflow we keep this color profile when converting to JPEG.

This files can be viewed and edited by various tools and browsers but current versions of Safari (on macOS and iOS 16) do not render this images at all. Neither in kitodo-presentation, DFG-Viewer nor directly opening the file in a browser window. On the other hand, with Safari on an older device running iOS 12.x everything looks as expected.

Example page: http://digi.bib.uni-mannheim.de/urn/urn:nbn:de:bsz:180-digsj-172
Example JPEG: https://digi.bib.uni-mannheim.de/fileadmin/statjahrb/514401303_1893/max/514401303_0001.jpg

Has anybody experienced similar rendering problems linked to embedded color profiles? Do you generally avoid embedding color profiles?

**Comment by stweil** [comment]
Safari 16.3 (18614.4.6.1.6) on macOS 13.2.1 displays the single JPEG file, but does not show the page image in Kitodo.Presentation (neither local nor in DFG viewer).

**Comment by stweil** [comment]
Cc'ing @frank-ulrich-weber. The scanner manufacturer may have more insight.

**Comment by stweil** [comment]
It looks like http://digitale-sammlungen.gwlb.de/content/862916992/862916992.xml has the same problem.

**Comment by mahaesin** [comment]
> It looks like http://digitale-sammlungen.gwlb.de/content/862916992/862916992.xml has the same problem.

While the viewer on that page ( https://digitale-sammlungen.gwlb.de/sammlungen/sammlungsliste/werksansicht?tx_dlf%5Bid%5D=1865 ) isn't rendered correctly with some/current web browsers due to "insecure" HTTP elements the JPEG-Image 
https://digitale-sammlungen.gwlb.de/content/862916992/jpgs/max/00000001.jpg 
is indeed another example of an image file that can't be displayed with Safari (iPadOS Version 16.2).
The color profile (`icc:copyright: Copyright by LOGO GmbH, Steinfurt   icc:description: OS14000_A2_B8_oG`) comes from a Zeutschel scanner as well.

**Comment by stweil** [comment]
@sebastian-meyer, I'm afraid that many METS files still use HTTP links for their images. Firefox with the DFG viewer won't show them because of "mixed content" with HTTPS and HTTP. Should we open a new issue for that?

**Comment by mahaesin** [comment]
It seems that safari now can handle our jpeg files with that embedded color profile in current versions. 
(Tested with iPadOS version 17.4 and MacOS version 14.4)
