### ISSUE TITLE
[BUG] Pagenavigation on sorted resultsets fails from page 2

### ISSUE THREAD

**Issue by michaelkubina** [kitodo/kitodo-presentation#928]
In the current version, sorting and direction selection on the first page seems to work. But as soon as you select other pages in the resultset, the complete search is lost. Also when selecting facets and sorting later, the selected facets are lost.

This is a critical issue, that should be fixed in the upcoming 4.1.0 release.

Structure:
Search plugin
Listview plugin

Procedure:
1. enter search term
2. select sorting on the result list
3. browse to the next page

Desired behavior:
The sorting parameters should be kept on the next pages and sorting with active facets should also be possible.

**Comment by sebastian-meyer** [comment]
This is fixed with #930, right?

**Comment by michaelkubina** [comment]
Yes, I will close this issue
