### ISSUE TITLE
[BUG] Get METS url with newest presentation version

### ISSUE THREAD

**Issue by csidirop** [kitodo/kitodo-presentation#968]
## Description

With presentation 3.3 there was a variable called `$uid` stored in a `Document` object. It holds the UID (solr indexed) or the URL (mets) of the document.
Now with presentation 4.x the mentioned variable is empty for all METS files I've tested (around 30) or any solr indexed documents. 

Is this on purpose or a bug? If on purpose, what would be the correct way to get the url?

## Reproduction

Try any METS files and check if `$doc->uid` (for PageView) or `$this->document->getDoc()` (PageViewController) is empty or not. 
Example: https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-512520879
But you can try any of those too: https://github.com/UB-Mannheim/kitodo-presentation/wiki/METS-Examples

## Environment

 - OS version: Debian
 - RDBMS version: Maria DB
 - Apache Solr version: -
 - TYPO3 version: 10.4.37
 - PHP version: 7.4.33

**Comment by csidirop** [comment]
Btw.: I went back till 6074cdfb5211e4fa2b984eb0b51f7837581bff72 from Mar. 2022 and the variable (and some more) is still empty. So maybe its since the Extbase/Fluid transition.

**Comment by csidirop** [comment]
As I have suspected, this issue appears after the Extbase/fluid transition ce36746d897fc960ff3980791f40539a1564a8eb . 

I digged a bit deeper. Prior to v4.x the [construct function of Document](https://github.com/kitodo/kitodo-presentation/blob/3.3.x/Classes/Common/Document.php#L1619) set the `$uid` var up. With v4.x the code moved to individual functions (one of those [init($location)](https://github.com/kitodo/kitodo-presentation/blob/master/Classes/Common/MetsDocument.php#L756)). 
Furthermore the $location parameter of the [construct function in Doc](https://github.com/kitodo/kitodo-presentation/blob/master/Classes/Common/Doc.php#L1168) was in every test empty. 

Then I realized that somehow I missed, that there is no `$uid` var any more in v.4.x even though a var_dump of the document object has it (even if its null) and its still referenced in the code (btw. adding type declarations would stop at those points).

**Comment by sebastian-meyer** [comment]
Closed this, because while it is true, that `uid` and `location` are no longer properties of `Doc` class, this is an intentional change. Those properties were moved to `DocumentRepository` and can be accessed there.
