### ISSUE TITLE
Fulltext button not showing

### ISSUE THREAD

**Issue by csidirop** [kitodo/kitodo-presentation#994]
## Description

Since the main branch got merged into the 4.x the fulltext button and the download links are not shown any more.

Version 4.x from 21 Jul 23: 38b64cad5d7ea630fe063556404af46c9244220e
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/c7dbbd7e-5138-4728-99aa-cdf018eb24e1)

## Reproduction

1. Update to newest presentation version
2. Open a document with fulltext

## Expected Behavior

The fulltext button should be shown if there is fulltext available.

Version 4.x from 16 Feb 23: 0c1dc276fccdb014e2080b8a25f9ca08a4f6fd48
![grafik](https://github.com/kitodo/kitodo-presentation/assets/43964592/81dd2ff4-60ad-47e5-9772-89ee8927c5c1)

## Environment

 -  OS version: Debian
 -  RDBMS version: MySQL 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204 
 -  Apache Solr version: 8.11.2 ([docker](https://hub.docker.com/_/solr/))
 -  TYPO3 version: 10.4.38-dev
 -  PHP version: 7.4.33

**Comment by csidirop** [comment]
So I digged a bit into that. The fulltext button stopped showing somewhere between the commits 38e759b1a1915904ff2c391fb2d1f1b9f36a33bb and 0054abb0f16369ed363b3bf0fc730e7c50cb92a7. Unfortunately lead the first commit to errors (which were handled only in the last commit), so its not clear where exactly the error is.

**Comment by beatrycze-volk** [comment]
Thanks for pointing out the commits which introduced the problem.

Could you write down your plugin configuration?

**Comment by csidirop** [comment]
Thanks for your reply!

Which plugin configuration do you mean? 

In the meantime I found out, that the error first occurs in this commit 38e759b1a1915904ff2c391fb2d1f1b9f36a33bb. If I revert the changes in ToolboxController the fulltext button is shown again. So the other changes have nothing to do with that error.

**Comment by beatrycze-volk** [comment]
> 
> Which plugin configuration do you mean?
> 

I would need to know how your tools are called in typo script setup.

<img width="215" alt="tools" src="https://github.com/kitodo/kitodo-presentation/assets/9614459/f85958b2-f0f3-475b-9355-395357d4b6c4">

**Comment by csidirop** [comment]
I did not change any default values on purpose.

_dfgviewer/Configuration/TypoScript/Plugins/kitodo.typoscript_:

```
...

# --------------------------------------------------------------------------------------------------------------------
# Tools like imagemanipulation, fulltext and downloads eg.
# --------------------------------------------------------------------------------------------------------------------

# available tools:

# fulltexttool
# annotationtool
# fulltextdownloadtool
# imagedownloadtool
# imagemanipulationtool
# pdfdownloadtool
# searchindocumenttool

plugin.tx_dlf_toolbox < tt_content.list.20.dlf_toolbox
plugin.tx_dlf_toolbox {
    settings {
#        fileGrpsImageDownload = MIN,DEFAULT,MAX
    }
}

plugin.tx_dlf_fulltexttool < plugin.tx_dlf_toolbox
plugin.tx_dlf_fulltexttool {
    settings {
        tools = fulltexttool
        activateFullTextInitially = 0
        fullTextScrollElement = html, body
    }
}

plugin.tx_dlf_imagemanipulationtool < plugin.tx_dlf_toolbox
plugin.tx_dlf_imagemanipulationtool {
    settings {
        tools = imagemanipulationtool
    }
}

plugin.tx_dlf_pdfdownloadtool < plugin.tx_dlf_toolbox
plugin.tx_dlf_pdfdownloadtool {
    settings {
        tools = pdfdownloadtool
    }
}

...
```


_dlf/Configuration/TypoScript/Toolbox/setup.typoscript_:
```
plugin.tx_dlf_fulltexttool {
    settings {
        activateFullTextInitially = 0
        fullTextScrollElement = html, body
        searchHlParameters = tx_dlf[highlight_word]
    }
}

plugin.tx_dlf_searchindocumenttool {
    settings {
        searchUrl =
        documentIdUrlSchema =
        idInputName = tx_dlf[id]
        queryInputName = tx_dlf[query]
        startInputName = tx_dlf[start]
        pageInputName = tx_dlf[page]
        highlightWordInputName = tx_dlf[highlight_word]
        encryptedInputName = tx_dlf[encrypted]
    }
}
```

**Comment by csidirop** [comment]
Not sure if this helps, but `renderFulltextTool()` is called and the if-block at [line 181](https://github.com/kitodo/kitodo-presentation/blob/4.x/Classes/Controller/ToolboxController.php#L181) is executed. 

My guess was, that there is some other reference broken here. But I did not found any.

**Comment by beatrycze-volk** [comment]
Thank you very much! It actually helped a lot. I think I know what is the problem and I have made a fix for it.
